//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/Personal/Documents/raspi-config/client-framework/build/j2oSources/com/google/common/util/concurrent/ExecutionError.java
//

#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "com/google/common/util/concurrent/ExecutionError.h"
#include "java/lang/Error.h"
#include "java/lang/annotation/Annotation.h"
#include "javax/annotation/Nullable.h"

inline jlong ComGoogleCommonUtilConcurrentExecutionError_get_serialVersionUID();
#define ComGoogleCommonUtilConcurrentExecutionError_serialVersionUID 0LL
J2OBJC_STATIC_FIELD_CONSTANT(ComGoogleCommonUtilConcurrentExecutionError, serialVersionUID, jlong)

__attribute__((unused)) static IOSObjectArray *ComGoogleCommonUtilConcurrentExecutionError__Annotations$0();

__attribute__((unused)) static IOSObjectArray *ComGoogleCommonUtilConcurrentExecutionError__Annotations$1();

__attribute__((unused)) static IOSObjectArray *ComGoogleCommonUtilConcurrentExecutionError__Annotations$2();

@implementation ComGoogleCommonUtilConcurrentExecutionError

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ComGoogleCommonUtilConcurrentExecutionError_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (instancetype)initWithNSString:(NSString *)message {
  ComGoogleCommonUtilConcurrentExecutionError_initWithNSString_(self, message);
  return self;
}

- (instancetype)initWithNSString:(NSString *)message
               withJavaLangError:(JavaLangError *)cause {
  ComGoogleCommonUtilConcurrentExecutionError_initWithNSString_withJavaLangError_(self, message, cause);
  return self;
}

- (instancetype)initWithJavaLangError:(JavaLangError *)cause {
  ComGoogleCommonUtilConcurrentExecutionError_initWithJavaLangError_(self, cause);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x4, -1, -1, -1, -1, -1, -1 },
    { NULL, NULL, 0x4, -1, 0, -1, -1, -1, 1 },
    { NULL, NULL, 0x1, -1, 2, -1, -1, -1, 3 },
    { NULL, NULL, 0x1, -1, 4, -1, -1, -1, 5 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(initWithNSString:);
  methods[2].selector = @selector(initWithNSString:withJavaLangError:);
  methods[3].selector = @selector(initWithJavaLangError:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "serialVersionUID", "J", .constantValue.asLong = ComGoogleCommonUtilConcurrentExecutionError_serialVersionUID, 0x1a, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LNSString;", (void *)&ComGoogleCommonUtilConcurrentExecutionError__Annotations$0, "LNSString;LJavaLangError;", (void *)&ComGoogleCommonUtilConcurrentExecutionError__Annotations$1, "LJavaLangError;", (void *)&ComGoogleCommonUtilConcurrentExecutionError__Annotations$2 };
  static const J2ObjcClassInfo _ComGoogleCommonUtilConcurrentExecutionError = { "ExecutionError", "com.google.common.util.concurrent", ptrTable, methods, fields, 7, 0x1, 4, 1, -1, -1, -1, -1, -1 };
  return &_ComGoogleCommonUtilConcurrentExecutionError;
}

@end

void ComGoogleCommonUtilConcurrentExecutionError_init(ComGoogleCommonUtilConcurrentExecutionError *self) {
  JavaLangError_init(self);
}

ComGoogleCommonUtilConcurrentExecutionError *new_ComGoogleCommonUtilConcurrentExecutionError_init() {
  J2OBJC_NEW_IMPL(ComGoogleCommonUtilConcurrentExecutionError, init)
}

ComGoogleCommonUtilConcurrentExecutionError *create_ComGoogleCommonUtilConcurrentExecutionError_init() {
  J2OBJC_CREATE_IMPL(ComGoogleCommonUtilConcurrentExecutionError, init)
}

void ComGoogleCommonUtilConcurrentExecutionError_initWithNSString_(ComGoogleCommonUtilConcurrentExecutionError *self, NSString *message) {
  JavaLangError_initWithNSString_(self, message);
}

ComGoogleCommonUtilConcurrentExecutionError *new_ComGoogleCommonUtilConcurrentExecutionError_initWithNSString_(NSString *message) {
  J2OBJC_NEW_IMPL(ComGoogleCommonUtilConcurrentExecutionError, initWithNSString_, message)
}

ComGoogleCommonUtilConcurrentExecutionError *create_ComGoogleCommonUtilConcurrentExecutionError_initWithNSString_(NSString *message) {
  J2OBJC_CREATE_IMPL(ComGoogleCommonUtilConcurrentExecutionError, initWithNSString_, message)
}

void ComGoogleCommonUtilConcurrentExecutionError_initWithNSString_withJavaLangError_(ComGoogleCommonUtilConcurrentExecutionError *self, NSString *message, JavaLangError *cause) {
  JavaLangError_initWithNSString_withNSException_(self, message, cause);
}

ComGoogleCommonUtilConcurrentExecutionError *new_ComGoogleCommonUtilConcurrentExecutionError_initWithNSString_withJavaLangError_(NSString *message, JavaLangError *cause) {
  J2OBJC_NEW_IMPL(ComGoogleCommonUtilConcurrentExecutionError, initWithNSString_withJavaLangError_, message, cause)
}

ComGoogleCommonUtilConcurrentExecutionError *create_ComGoogleCommonUtilConcurrentExecutionError_initWithNSString_withJavaLangError_(NSString *message, JavaLangError *cause) {
  J2OBJC_CREATE_IMPL(ComGoogleCommonUtilConcurrentExecutionError, initWithNSString_withJavaLangError_, message, cause)
}

void ComGoogleCommonUtilConcurrentExecutionError_initWithJavaLangError_(ComGoogleCommonUtilConcurrentExecutionError *self, JavaLangError *cause) {
  JavaLangError_initWithNSException_(self, cause);
}

ComGoogleCommonUtilConcurrentExecutionError *new_ComGoogleCommonUtilConcurrentExecutionError_initWithJavaLangError_(JavaLangError *cause) {
  J2OBJC_NEW_IMPL(ComGoogleCommonUtilConcurrentExecutionError, initWithJavaLangError_, cause)
}

ComGoogleCommonUtilConcurrentExecutionError *create_ComGoogleCommonUtilConcurrentExecutionError_initWithJavaLangError_(JavaLangError *cause) {
  J2OBJC_CREATE_IMPL(ComGoogleCommonUtilConcurrentExecutionError, initWithJavaLangError_, cause)
}

IOSObjectArray *ComGoogleCommonUtilConcurrentExecutionError__Annotations$0() {
  return [IOSObjectArray newArrayWithObjects:(id[]){ [IOSObjectArray newArrayWithObjects:(id[]){ create_JavaxAnnotationNullable() } count:1 type:JavaLangAnnotationAnnotation_class_()] } count:1 type:IOSClass_arrayType(JavaLangAnnotationAnnotation_class_(), 1)];
}

IOSObjectArray *ComGoogleCommonUtilConcurrentExecutionError__Annotations$1() {
  return [IOSObjectArray newArrayWithObjects:(id[]){ [IOSObjectArray newArrayWithObjects:(id[]){ create_JavaxAnnotationNullable() } count:1 type:JavaLangAnnotationAnnotation_class_()], [IOSObjectArray newArrayWithObjects:(id[]){ create_JavaxAnnotationNullable() } count:1 type:JavaLangAnnotationAnnotation_class_()] } count:2 type:IOSClass_arrayType(JavaLangAnnotationAnnotation_class_(), 1)];
}

IOSObjectArray *ComGoogleCommonUtilConcurrentExecutionError__Annotations$2() {
  return [IOSObjectArray newArrayWithObjects:(id[]){ [IOSObjectArray newArrayWithObjects:(id[]){ create_JavaxAnnotationNullable() } count:1 type:JavaLangAnnotationAnnotation_class_()] } count:1 type:IOSClass_arrayType(JavaLangAnnotationAnnotation_class_(), 1)];
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComGoogleCommonUtilConcurrentExecutionError)
