//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/Personal/Documents/raspi-config/client-framework/build/j2oSources/com/google/common/base/Platform.java
//

#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "com/google/common/base/CharMatcher.h"
#include "com/google/common/base/CommonPattern.h"
#include "com/google/common/base/Enums.h"
#include "com/google/common/base/JdkPattern.h"
#include "com/google/common/base/Optional.h"
#include "com/google/common/base/PatternCompiler.h"
#include "com/google/common/base/Platform.h"
#include "com/google/common/base/Preconditions.h"
#include "java/lang/Double.h"
#include "java/lang/Enum.h"
#include "java/lang/System.h"
#include "java/lang/annotation/Annotation.h"
#include "java/lang/ref/WeakReference.h"
#include "java/util/Iterator.h"
#include "java/util/Locale.h"
#include "java/util/Map.h"
#include "java/util/ServiceConfigurationError.h"
#include "java/util/ServiceLoader.h"
#include "java/util/logging/Level.h"
#include "java/util/logging/Logger.h"
#include "java/util/regex/Pattern.h"
#include "javax/annotation/Nullable.h"

@interface ComGoogleCommonBasePlatform ()

- (instancetype)init;

+ (id<ComGoogleCommonBasePatternCompiler>)loadPatternCompiler;

+ (void)logPatternCompilerErrorWithJavaUtilServiceConfigurationError:(JavaUtilServiceConfigurationError *)e;

@end

inline JavaUtilLoggingLogger *ComGoogleCommonBasePlatform_get_logger();
static JavaUtilLoggingLogger *ComGoogleCommonBasePlatform_logger;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonBasePlatform, logger, JavaUtilLoggingLogger *)

inline id<ComGoogleCommonBasePatternCompiler> ComGoogleCommonBasePlatform_get_patternCompiler();
static id<ComGoogleCommonBasePatternCompiler> ComGoogleCommonBasePlatform_patternCompiler;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonBasePlatform, patternCompiler, id<ComGoogleCommonBasePatternCompiler>)

__attribute__((unused)) static void ComGoogleCommonBasePlatform_init(ComGoogleCommonBasePlatform *self);

__attribute__((unused)) static ComGoogleCommonBasePlatform *new_ComGoogleCommonBasePlatform_init() NS_RETURNS_RETAINED;

__attribute__((unused)) static ComGoogleCommonBasePlatform *create_ComGoogleCommonBasePlatform_init();

__attribute__((unused)) static id<ComGoogleCommonBasePatternCompiler> ComGoogleCommonBasePlatform_loadPatternCompiler();

__attribute__((unused)) static void ComGoogleCommonBasePlatform_logPatternCompilerErrorWithJavaUtilServiceConfigurationError_(JavaUtilServiceConfigurationError *e);

__attribute__((unused)) static IOSObjectArray *ComGoogleCommonBasePlatform__Annotations$0();

@interface ComGoogleCommonBasePlatform_JdkPatternCompiler : NSObject < ComGoogleCommonBasePatternCompiler >

- (instancetype)init;

- (ComGoogleCommonBaseCommonPattern *)compileWithNSString:(NSString *)pattern;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonBasePlatform_JdkPatternCompiler)

__attribute__((unused)) static void ComGoogleCommonBasePlatform_JdkPatternCompiler_init(ComGoogleCommonBasePlatform_JdkPatternCompiler *self);

__attribute__((unused)) static ComGoogleCommonBasePlatform_JdkPatternCompiler *new_ComGoogleCommonBasePlatform_JdkPatternCompiler_init() NS_RETURNS_RETAINED;

__attribute__((unused)) static ComGoogleCommonBasePlatform_JdkPatternCompiler *create_ComGoogleCommonBasePlatform_JdkPatternCompiler_init();

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonBasePlatform_JdkPatternCompiler)

J2OBJC_INITIALIZED_DEFN(ComGoogleCommonBasePlatform)

@implementation ComGoogleCommonBasePlatform

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ComGoogleCommonBasePlatform_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (jlong)systemNanoTime {
  return ComGoogleCommonBasePlatform_systemNanoTime();
}

+ (ComGoogleCommonBaseCharMatcher *)precomputeCharMatcherWithComGoogleCommonBaseCharMatcher:(ComGoogleCommonBaseCharMatcher *)matcher {
  return ComGoogleCommonBasePlatform_precomputeCharMatcherWithComGoogleCommonBaseCharMatcher_(matcher);
}

+ (ComGoogleCommonBaseOptional *)getEnumIfPresentWithIOSClass:(IOSClass *)enumClass
                                                 withNSString:(NSString *)value {
  return ComGoogleCommonBasePlatform_getEnumIfPresentWithIOSClass_withNSString_(enumClass, value);
}

+ (NSString *)formatCompact4DigitsWithDouble:(jdouble)value {
  return ComGoogleCommonBasePlatform_formatCompact4DigitsWithDouble_(value);
}

+ (jboolean)stringIsNullOrEmptyWithNSString:(NSString *)string {
  return ComGoogleCommonBasePlatform_stringIsNullOrEmptyWithNSString_(string);
}

+ (ComGoogleCommonBaseCommonPattern *)compilePatternWithNSString:(NSString *)pattern {
  return ComGoogleCommonBasePlatform_compilePatternWithNSString_(pattern);
}

+ (jboolean)usingJdkPatternCompiler {
  return ComGoogleCommonBasePlatform_usingJdkPatternCompiler();
}

+ (id<ComGoogleCommonBasePatternCompiler>)loadPatternCompiler {
  return ComGoogleCommonBasePlatform_loadPatternCompiler();
}

+ (void)logPatternCompilerErrorWithJavaUtilServiceConfigurationError:(JavaUtilServiceConfigurationError *)e {
  ComGoogleCommonBasePlatform_logPatternCompilerErrorWithJavaUtilServiceConfigurationError_(e);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x2, -1, -1, -1, -1, -1, -1 },
    { NULL, "J", 0x8, -1, -1, -1, -1, -1, -1 },
    { NULL, "LComGoogleCommonBaseCharMatcher;", 0x8, 0, 1, -1, -1, -1, -1 },
    { NULL, "LComGoogleCommonBaseOptional;", 0x8, 2, 3, -1, 4, -1, -1 },
    { NULL, "LNSString;", 0x8, 5, 6, -1, -1, -1, -1 },
    { NULL, "Z", 0x8, 7, 8, -1, -1, -1, 9 },
    { NULL, "LComGoogleCommonBaseCommonPattern;", 0x8, 10, 8, -1, -1, -1, -1 },
    { NULL, "Z", 0x8, -1, -1, -1, -1, -1, -1 },
    { NULL, "LComGoogleCommonBasePatternCompiler;", 0xa, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0xa, 11, 12, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(systemNanoTime);
  methods[2].selector = @selector(precomputeCharMatcherWithComGoogleCommonBaseCharMatcher:);
  methods[3].selector = @selector(getEnumIfPresentWithIOSClass:withNSString:);
  methods[4].selector = @selector(formatCompact4DigitsWithDouble:);
  methods[5].selector = @selector(stringIsNullOrEmptyWithNSString:);
  methods[6].selector = @selector(compilePatternWithNSString:);
  methods[7].selector = @selector(usingJdkPatternCompiler);
  methods[8].selector = @selector(loadPatternCompiler);
  methods[9].selector = @selector(logPatternCompilerErrorWithJavaUtilServiceConfigurationError:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "logger", "LJavaUtilLoggingLogger;", .constantValue.asLong = 0, 0x1a, -1, 13, -1, -1 },
    { "patternCompiler", "LComGoogleCommonBasePatternCompiler;", .constantValue.asLong = 0, 0x1a, -1, 14, -1, -1 },
  };
  static const void *ptrTable[] = { "precomputeCharMatcher", "LComGoogleCommonBaseCharMatcher;", "getEnumIfPresent", "LIOSClass;LNSString;", "<T:Ljava/lang/Enum<TT;>;>(Ljava/lang/Class<TT;>;Ljava/lang/String;)Lcom/google/common/base/Optional<TT;>;", "formatCompact4Digits", "D", "stringIsNullOrEmpty", "LNSString;", (void *)&ComGoogleCommonBasePlatform__Annotations$0, "compilePattern", "logPatternCompilerError", "LJavaUtilServiceConfigurationError;", &ComGoogleCommonBasePlatform_logger, &ComGoogleCommonBasePlatform_patternCompiler, "LComGoogleCommonBasePlatform_JdkPatternCompiler;" };
  static const J2ObjcClassInfo _ComGoogleCommonBasePlatform = { "Platform", "com.google.common.base", ptrTable, methods, fields, 7, 0x10, 10, 2, -1, 15, -1, -1, -1 };
  return &_ComGoogleCommonBasePlatform;
}

+ (void)initialize {
  if (self == [ComGoogleCommonBasePlatform class]) {
    ComGoogleCommonBasePlatform_logger = JavaUtilLoggingLogger_getLoggerWithNSString_([ComGoogleCommonBasePlatform_class_() getName]);
    ComGoogleCommonBasePlatform_patternCompiler = ComGoogleCommonBasePlatform_loadPatternCompiler();
    J2OBJC_SET_INITIALIZED(ComGoogleCommonBasePlatform)
  }
}

@end

void ComGoogleCommonBasePlatform_init(ComGoogleCommonBasePlatform *self) {
  NSObject_init(self);
}

ComGoogleCommonBasePlatform *new_ComGoogleCommonBasePlatform_init() {
  J2OBJC_NEW_IMPL(ComGoogleCommonBasePlatform, init)
}

ComGoogleCommonBasePlatform *create_ComGoogleCommonBasePlatform_init() {
  J2OBJC_CREATE_IMPL(ComGoogleCommonBasePlatform, init)
}

jlong ComGoogleCommonBasePlatform_systemNanoTime() {
  ComGoogleCommonBasePlatform_initialize();
  return JavaLangSystem_nanoTime();
}

ComGoogleCommonBaseCharMatcher *ComGoogleCommonBasePlatform_precomputeCharMatcherWithComGoogleCommonBaseCharMatcher_(ComGoogleCommonBaseCharMatcher *matcher) {
  ComGoogleCommonBasePlatform_initialize();
  return [((ComGoogleCommonBaseCharMatcher *) nil_chk(matcher)) precomputedInternal];
}

ComGoogleCommonBaseOptional *ComGoogleCommonBasePlatform_getEnumIfPresentWithIOSClass_withNSString_(IOSClass *enumClass, NSString *value) {
  ComGoogleCommonBasePlatform_initialize();
  JavaLangRefWeakReference *ref = [((id<JavaUtilMap>) nil_chk(ComGoogleCommonBaseEnums_getEnumConstantsWithIOSClass_(enumClass))) getWithId:value];
  return ref == nil ? ComGoogleCommonBaseOptional_absent() : ComGoogleCommonBaseOptional_ofWithId_([((IOSClass *) nil_chk(enumClass)) cast:[ref get]]);
}

NSString *ComGoogleCommonBasePlatform_formatCompact4DigitsWithDouble_(jdouble value) {
  ComGoogleCommonBasePlatform_initialize();
  return NSString_java_formatWithJavaUtilLocale_withNSString_withNSObjectArray_(JreLoadStatic(JavaUtilLocale, ROOT), @"%.4g", [IOSObjectArray newArrayWithObjects:(id[]){ JavaLangDouble_valueOfWithDouble_(value) } count:1 type:NSObject_class_()]);
}

jboolean ComGoogleCommonBasePlatform_stringIsNullOrEmptyWithNSString_(NSString *string) {
  ComGoogleCommonBasePlatform_initialize();
  return string == nil || [string java_isEmpty];
}

ComGoogleCommonBaseCommonPattern *ComGoogleCommonBasePlatform_compilePatternWithNSString_(NSString *pattern) {
  ComGoogleCommonBasePlatform_initialize();
  (void) ComGoogleCommonBasePreconditions_checkNotNullWithId_(pattern);
  return [((id<ComGoogleCommonBasePatternCompiler>) nil_chk(ComGoogleCommonBasePlatform_patternCompiler)) compileWithNSString:pattern];
}

jboolean ComGoogleCommonBasePlatform_usingJdkPatternCompiler() {
  ComGoogleCommonBasePlatform_initialize();
  return [ComGoogleCommonBasePlatform_patternCompiler isKindOfClass:[ComGoogleCommonBasePlatform_JdkPatternCompiler class]];
}

id<ComGoogleCommonBasePatternCompiler> ComGoogleCommonBasePlatform_loadPatternCompiler() {
  ComGoogleCommonBasePlatform_initialize();
  JavaUtilServiceLoader *loader = JavaUtilServiceLoader_load__WithIOSClass_(ComGoogleCommonBasePatternCompiler_class_());
  @try {
    for (id<JavaUtilIterator> it = [((JavaUtilServiceLoader *) nil_chk(loader)) iterator]; [((id<JavaUtilIterator>) nil_chk(it)) hasNext]; ) {
      @try {
        return [it next];
      }
      @catch (JavaUtilServiceConfigurationError *e) {
        ComGoogleCommonBasePlatform_logPatternCompilerErrorWithJavaUtilServiceConfigurationError_(e);
      }
    }
  }
  @catch (JavaUtilServiceConfigurationError *e) {
    ComGoogleCommonBasePlatform_logPatternCompilerErrorWithJavaUtilServiceConfigurationError_(e);
  }
  return new_ComGoogleCommonBasePlatform_JdkPatternCompiler_init();
}

void ComGoogleCommonBasePlatform_logPatternCompilerErrorWithJavaUtilServiceConfigurationError_(JavaUtilServiceConfigurationError *e) {
  ComGoogleCommonBasePlatform_initialize();
  [((JavaUtilLoggingLogger *) nil_chk(ComGoogleCommonBasePlatform_logger)) logWithJavaUtilLoggingLevel:JreLoadStatic(JavaUtilLoggingLevel, WARNING) withNSString:@"Error loading regex compiler, falling back to next option" withNSException:e];
}

IOSObjectArray *ComGoogleCommonBasePlatform__Annotations$0() {
  return [IOSObjectArray newArrayWithObjects:(id[]){ [IOSObjectArray newArrayWithObjects:(id[]){ create_JavaxAnnotationNullable() } count:1 type:JavaLangAnnotationAnnotation_class_()] } count:1 type:IOSClass_arrayType(JavaLangAnnotationAnnotation_class_(), 1)];
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComGoogleCommonBasePlatform)

@implementation ComGoogleCommonBasePlatform_JdkPatternCompiler

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ComGoogleCommonBasePlatform_JdkPatternCompiler_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (ComGoogleCommonBaseCommonPattern *)compileWithNSString:(NSString *)pattern {
  return new_ComGoogleCommonBaseJdkPattern_initWithJavaUtilRegexPattern_(JavaUtilRegexPattern_compileWithNSString_(pattern));
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x2, -1, -1, -1, -1, -1, -1 },
    { NULL, "LComGoogleCommonBaseCommonPattern;", 0x1, 0, 1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(compileWithNSString:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "compile", "LNSString;", "LComGoogleCommonBasePlatform;" };
  static const J2ObjcClassInfo _ComGoogleCommonBasePlatform_JdkPatternCompiler = { "JdkPatternCompiler", "com.google.common.base", ptrTable, methods, NULL, 7, 0x1a, 2, 0, 2, -1, -1, -1, -1 };
  return &_ComGoogleCommonBasePlatform_JdkPatternCompiler;
}

@end

void ComGoogleCommonBasePlatform_JdkPatternCompiler_init(ComGoogleCommonBasePlatform_JdkPatternCompiler *self) {
  NSObject_init(self);
}

ComGoogleCommonBasePlatform_JdkPatternCompiler *new_ComGoogleCommonBasePlatform_JdkPatternCompiler_init() {
  J2OBJC_NEW_IMPL(ComGoogleCommonBasePlatform_JdkPatternCompiler, init)
}

ComGoogleCommonBasePlatform_JdkPatternCompiler *create_ComGoogleCommonBasePlatform_JdkPatternCompiler_init() {
  J2OBJC_CREATE_IMPL(ComGoogleCommonBasePlatform_JdkPatternCompiler, init)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComGoogleCommonBasePlatform_JdkPatternCompiler)
