//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/Personal/Documents/raspi-config/client-framework/build/j2oSources/com/google/common/hash/Hasher.java
//

#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "com/google/common/hash/Hasher.h"
#include "java/lang/Deprecated.h"
#include "java/lang/annotation/Annotation.h"

@interface ComGoogleCommonHashHasher : NSObject

@end

__attribute__((unused)) static IOSObjectArray *ComGoogleCommonHashHasher__Annotations$0();

@implementation ComGoogleCommonHashHasher

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "LComGoogleCommonHashHasher;", 0x401, 0, 1, -1, -1, -1, -1 },
    { NULL, "LComGoogleCommonHashHasher;", 0x401, 2, 3, -1, -1, -1, -1 },
    { NULL, "LComGoogleCommonHashHasher;", 0x401, 2, 4, -1, -1, -1, -1 },
    { NULL, "LComGoogleCommonHashHasher;", 0x401, 5, 6, -1, -1, -1, -1 },
    { NULL, "LComGoogleCommonHashHasher;", 0x401, 7, 8, -1, -1, -1, -1 },
    { NULL, "LComGoogleCommonHashHasher;", 0x401, 9, 10, -1, -1, -1, -1 },
    { NULL, "LComGoogleCommonHashHasher;", 0x401, 11, 12, -1, -1, -1, -1 },
    { NULL, "LComGoogleCommonHashHasher;", 0x401, 13, 14, -1, -1, -1, -1 },
    { NULL, "LComGoogleCommonHashHasher;", 0x401, 15, 16, -1, -1, -1, -1 },
    { NULL, "LComGoogleCommonHashHasher;", 0x401, 17, 18, -1, -1, -1, -1 },
    { NULL, "LComGoogleCommonHashHasher;", 0x401, 19, 20, -1, -1, -1, -1 },
    { NULL, "LComGoogleCommonHashHasher;", 0x401, 21, 22, -1, -1, -1, -1 },
    { NULL, "LComGoogleCommonHashHasher;", 0x401, 23, 24, -1, 25, -1, -1 },
    { NULL, "LComGoogleCommonHashHashCode;", 0x401, 26, -1, -1, -1, -1, -1 },
    { NULL, "I", 0x401, 27, -1, -1, -1, 28, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(putByteWithByte:);
  methods[1].selector = @selector(putBytesWithByteArray:);
  methods[2].selector = @selector(putBytesWithByteArray:withInt:withInt:);
  methods[3].selector = @selector(putShortWithShort:);
  methods[4].selector = @selector(putIntWithInt:);
  methods[5].selector = @selector(putLongWithLong:);
  methods[6].selector = @selector(putFloatWithFloat:);
  methods[7].selector = @selector(putDoubleWithDouble:);
  methods[8].selector = @selector(putBooleanWithBoolean:);
  methods[9].selector = @selector(putCharWithChar:);
  methods[10].selector = @selector(putUnencodedCharsWithJavaLangCharSequence:);
  methods[11].selector = @selector(putStringWithJavaLangCharSequence:withJavaNioCharsetCharset:);
  methods[12].selector = @selector(putObjectWithId:withComGoogleCommonHashFunnel:);
  methods[13].selector = @selector(hash__);
  methods[14].selector = @selector(hash);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "putByte", "B", "putBytes", "[B", "[BII", "putShort", "S", "putInt", "I", "putLong", "J", "putFloat", "F", "putDouble", "D", "putBoolean", "Z", "putChar", "C", "putUnencodedChars", "LJavaLangCharSequence;", "putString", "LJavaLangCharSequence;LJavaNioCharsetCharset;", "putObject", "LNSObject;LComGoogleCommonHashFunnel;", "<T:Ljava/lang/Object;>(TT;Lcom/google/common/hash/Funnel<-TT;>;)Lcom/google/common/hash/Hasher;", "hash", "hashCode", (void *)&ComGoogleCommonHashHasher__Annotations$0 };
  static const J2ObjcClassInfo _ComGoogleCommonHashHasher = { "Hasher", "com.google.common.hash", ptrTable, methods, NULL, 7, 0x609, 15, 0, -1, -1, -1, -1, -1 };
  return &_ComGoogleCommonHashHasher;
}

@end

IOSObjectArray *ComGoogleCommonHashHasher__Annotations$0() {
  return [IOSObjectArray newArrayWithObjects:(id[]){ create_JavaLangDeprecated() } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(ComGoogleCommonHashHasher)
