//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/Personal/Documents/raspi-config/client-framework/build/j2oSources/com/google/common/graph/AbstractGraphBuilder.java
//

#include "J2ObjC_source.h"
#include "com/google/common/base/Optional.h"
#include "com/google/common/graph/AbstractGraphBuilder.h"
#include "com/google/common/graph/ElementOrder.h"

@implementation ComGoogleCommonGraphAbstractGraphBuilder

- (instancetype)initWithBoolean:(jboolean)directed {
  ComGoogleCommonGraphAbstractGraphBuilder_initWithBoolean_(self, directed);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x0, -1, 0, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(initWithBoolean:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "directed_", "Z", .constantValue.asLong = 0, 0x10, -1, -1, -1, -1 },
    { "allowsSelfLoops_", "Z", .constantValue.asLong = 0, 0x0, -1, -1, -1, -1 },
    { "nodeOrder_", "LComGoogleCommonGraphElementOrder;", .constantValue.asLong = 0, 0x0, -1, -1, 1, -1 },
    { "expectedNodeCount_", "LComGoogleCommonBaseOptional;", .constantValue.asLong = 0, 0x0, -1, -1, 2, -1 },
  };
  static const void *ptrTable[] = { "Z", "Lcom/google/common/graph/ElementOrder<TN;>;", "Lcom/google/common/base/Optional<Ljava/lang/Integer;>;", "<N:Ljava/lang/Object;>Ljava/lang/Object;" };
  static const J2ObjcClassInfo _ComGoogleCommonGraphAbstractGraphBuilder = { "AbstractGraphBuilder", "com.google.common.graph", ptrTable, methods, fields, 7, 0x400, 1, 4, -1, -1, -1, 3, -1 };
  return &_ComGoogleCommonGraphAbstractGraphBuilder;
}

@end

void ComGoogleCommonGraphAbstractGraphBuilder_initWithBoolean_(ComGoogleCommonGraphAbstractGraphBuilder *self, jboolean directed) {
  NSObject_init(self);
  self->allowsSelfLoops_ = false;
  self->nodeOrder_ = ComGoogleCommonGraphElementOrder_insertion();
  self->expectedNodeCount_ = ComGoogleCommonBaseOptional_absent();
  self->directed_ = directed;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComGoogleCommonGraphAbstractGraphBuilder)
