//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/Personal/Documents/raspi-config/client-framework/build/j2oSources/com/google/common/collect/ForwardingListMultimap.java
//

#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "com/google/common/collect/ForwardingListMultimap.h"
#include "com/google/common/collect/ForwardingMultimap.h"
#include "com/google/common/collect/ListMultimap.h"
#include "java/lang/Iterable.h"
#include "java/lang/annotation/Annotation.h"
#include "java/util/List.h"
#include "javax/annotation/Nullable.h"

__attribute__((unused)) static IOSObjectArray *ComGoogleCommonCollectForwardingListMultimap__Annotations$0();

__attribute__((unused)) static IOSObjectArray *ComGoogleCommonCollectForwardingListMultimap__Annotations$1();

@implementation ComGoogleCommonCollectForwardingListMultimap

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ComGoogleCommonCollectForwardingListMultimap_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (id<ComGoogleCommonCollectListMultimap>)delegate {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (id<JavaUtilList>)getWithId:(id)key {
  return [((id<ComGoogleCommonCollectListMultimap>) nil_chk([self delegate])) getWithId:key];
}

- (id<JavaUtilList>)removeAllWithId:(id)key {
  return [((id<ComGoogleCommonCollectListMultimap>) nil_chk([self delegate])) removeAllWithId:key];
}

- (id<JavaUtilList>)replaceValuesWithId:(id)key
                   withJavaLangIterable:(id<JavaLangIterable>)values {
  return [((id<ComGoogleCommonCollectListMultimap>) nil_chk([self delegate])) replaceValuesWithId:key withJavaLangIterable:values];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x4, -1, -1, -1, -1, -1, -1 },
    { NULL, "LComGoogleCommonCollectListMultimap;", 0x404, -1, -1, -1, 0, -1, -1 },
    { NULL, "LJavaUtilList;", 0x1, 1, 2, -1, 3, -1, 4 },
    { NULL, "LJavaUtilList;", 0x1, 5, 2, -1, 6, -1, 7 },
    { NULL, "LJavaUtilList;", 0x1, 8, 9, -1, 10, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(delegate);
  methods[2].selector = @selector(getWithId:);
  methods[3].selector = @selector(removeAllWithId:);
  methods[4].selector = @selector(replaceValuesWithId:withJavaLangIterable:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "()Lcom/google/common/collect/ListMultimap<TK;TV;>;", "get", "LNSObject;", "(TK;)Ljava/util/List<TV;>;", (void *)&ComGoogleCommonCollectForwardingListMultimap__Annotations$0, "removeAll", "(Ljava/lang/Object;)Ljava/util/List<TV;>;", (void *)&ComGoogleCommonCollectForwardingListMultimap__Annotations$1, "replaceValues", "LNSObject;LJavaLangIterable;", "(TK;Ljava/lang/Iterable<+TV;>;)Ljava/util/List<TV;>;", "<K:Ljava/lang/Object;V:Ljava/lang/Object;>Lcom/google/common/collect/ForwardingMultimap<TK;TV;>;Lcom/google/common/collect/ListMultimap<TK;TV;>;" };
  static const J2ObjcClassInfo _ComGoogleCommonCollectForwardingListMultimap = { "ForwardingListMultimap", "com.google.common.collect", ptrTable, methods, NULL, 7, 0x401, 5, 0, -1, -1, -1, 11, -1 };
  return &_ComGoogleCommonCollectForwardingListMultimap;
}

@end

void ComGoogleCommonCollectForwardingListMultimap_init(ComGoogleCommonCollectForwardingListMultimap *self) {
  ComGoogleCommonCollectForwardingMultimap_init(self);
}

IOSObjectArray *ComGoogleCommonCollectForwardingListMultimap__Annotations$0() {
  return [IOSObjectArray newArrayWithObjects:(id[]){ [IOSObjectArray newArrayWithObjects:(id[]){ create_JavaxAnnotationNullable() } count:1 type:JavaLangAnnotationAnnotation_class_()] } count:1 type:IOSClass_arrayType(JavaLangAnnotationAnnotation_class_(), 1)];
}

IOSObjectArray *ComGoogleCommonCollectForwardingListMultimap__Annotations$1() {
  return [IOSObjectArray newArrayWithObjects:(id[]){ [IOSObjectArray newArrayWithObjects:(id[]){ create_JavaxAnnotationNullable() } count:1 type:JavaLangAnnotationAnnotation_class_()] } count:1 type:IOSClass_arrayType(JavaLangAnnotationAnnotation_class_(), 1)];
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComGoogleCommonCollectForwardingListMultimap)
