//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/Personal/Documents/raspi-config/client-framework/build/j2oSources/com/google/common/collect/ForwardingImmutableSet.java
//

#include "J2ObjC_source.h"
#include "com/google/common/collect/ForwardingImmutableSet.h"

@interface ComGoogleCommonCollectForwardingImmutableSet ()

- (instancetype)init;

@end

__attribute__((unused)) static void ComGoogleCommonCollectForwardingImmutableSet_init(ComGoogleCommonCollectForwardingImmutableSet *self);

@implementation ComGoogleCommonCollectForwardingImmutableSet

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ComGoogleCommonCollectForwardingImmutableSet_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x2, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "<E:Ljava/lang/Object;>Ljava/lang/Object;" };
  static const J2ObjcClassInfo _ComGoogleCommonCollectForwardingImmutableSet = { "ForwardingImmutableSet", "com.google.common.collect", ptrTable, methods, NULL, 7, 0x400, 1, 0, -1, -1, -1, 0, -1 };
  return &_ComGoogleCommonCollectForwardingImmutableSet;
}

@end

void ComGoogleCommonCollectForwardingImmutableSet_init(ComGoogleCommonCollectForwardingImmutableSet *self) {
  NSObject_init(self);
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComGoogleCommonCollectForwardingImmutableSet)
