//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/Personal/Documents/raspi-config/client-framework/build/j2oSources/com/google/common/collect/MinMaxPriorityQueue.java
//

#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "com/google/common/base/Preconditions.h"
#include "com/google/common/collect/CollectPreconditions.h"
#include "com/google/common/collect/MinMaxPriorityQueue.h"
#include "com/google/common/collect/Ordering.h"
#include "com/google/common/math/IntMath.h"
#include "java/lang/Integer.h"
#include "java/lang/Iterable.h"
#include "java/lang/Math.h"
#include "java/lang/System.h"
#include "java/util/AbstractQueue.h"
#include "java/util/ArrayDeque.h"
#include "java/util/ArrayList.h"
#include "java/util/Collection.h"
#include "java/util/Collections.h"
#include "java/util/Comparator.h"
#include "java/util/ConcurrentModificationException.h"
#include "java/util/Iterator.h"
#include "java/util/List.h"
#include "java/util/NoSuchElementException.h"
#include "java/util/Queue.h"
#include "java/util/Set.h"
#include "java/util/function/Consumer.h"

@class ComGoogleCommonCollectMinMaxPriorityQueue_Heap;

@interface ComGoogleCommonCollectMinMaxPriorityQueue () {
 @public
  ComGoogleCommonCollectMinMaxPriorityQueue_Heap *minHeap_;
  ComGoogleCommonCollectMinMaxPriorityQueue_Heap *maxHeap_;
  IOSObjectArray *queue_;
  jint size_;
  jint modCount_;
}

- (instancetype)initWithComGoogleCommonCollectMinMaxPriorityQueue_Builder:(ComGoogleCommonCollectMinMaxPriorityQueue_Builder *)builder
                                                                  withInt:(jint)queueSize;

- (jint)getMaxElementIndex;

- (ComGoogleCommonCollectMinMaxPriorityQueue_MoveDesc *)fillHoleWithInt:(jint)index
                                                                 withId:(id)toTrickle;

- (id)removeAndGetWithInt:(jint)index;

- (ComGoogleCommonCollectMinMaxPriorityQueue_Heap *)heapForIndexWithInt:(jint)i;

- (void)growIfNeeded;

- (jint)calculateNewCapacity;

+ (jint)capAtMaximumSizeWithInt:(jint)queueSize
                        withInt:(jint)maximumSize;

@end

J2OBJC_FIELD_SETTER(ComGoogleCommonCollectMinMaxPriorityQueue, minHeap_, ComGoogleCommonCollectMinMaxPriorityQueue_Heap *)
J2OBJC_FIELD_SETTER(ComGoogleCommonCollectMinMaxPriorityQueue, maxHeap_, ComGoogleCommonCollectMinMaxPriorityQueue_Heap *)
J2OBJC_FIELD_SETTER(ComGoogleCommonCollectMinMaxPriorityQueue, queue_, IOSObjectArray *)

inline jint ComGoogleCommonCollectMinMaxPriorityQueue_get_EVEN_POWERS_OF_TWO();
#define ComGoogleCommonCollectMinMaxPriorityQueue_EVEN_POWERS_OF_TWO 1431655765
J2OBJC_STATIC_FIELD_CONSTANT(ComGoogleCommonCollectMinMaxPriorityQueue, EVEN_POWERS_OF_TWO, jint)

inline jint ComGoogleCommonCollectMinMaxPriorityQueue_get_ODD_POWERS_OF_TWO();
#define ComGoogleCommonCollectMinMaxPriorityQueue_ODD_POWERS_OF_TWO -1431655766
J2OBJC_STATIC_FIELD_CONSTANT(ComGoogleCommonCollectMinMaxPriorityQueue, ODD_POWERS_OF_TWO, jint)

inline jint ComGoogleCommonCollectMinMaxPriorityQueue_get_DEFAULT_CAPACITY();
#define ComGoogleCommonCollectMinMaxPriorityQueue_DEFAULT_CAPACITY 11
J2OBJC_STATIC_FIELD_CONSTANT(ComGoogleCommonCollectMinMaxPriorityQueue, DEFAULT_CAPACITY, jint)

__attribute__((unused)) static void ComGoogleCommonCollectMinMaxPriorityQueue_initWithComGoogleCommonCollectMinMaxPriorityQueue_Builder_withInt_(ComGoogleCommonCollectMinMaxPriorityQueue *self, ComGoogleCommonCollectMinMaxPriorityQueue_Builder *builder, jint queueSize);

__attribute__((unused)) static ComGoogleCommonCollectMinMaxPriorityQueue *new_ComGoogleCommonCollectMinMaxPriorityQueue_initWithComGoogleCommonCollectMinMaxPriorityQueue_Builder_withInt_(ComGoogleCommonCollectMinMaxPriorityQueue_Builder *builder, jint queueSize) NS_RETURNS_RETAINED;

__attribute__((unused)) static ComGoogleCommonCollectMinMaxPriorityQueue *create_ComGoogleCommonCollectMinMaxPriorityQueue_initWithComGoogleCommonCollectMinMaxPriorityQueue_Builder_withInt_(ComGoogleCommonCollectMinMaxPriorityQueue_Builder *builder, jint queueSize);

__attribute__((unused)) static jint ComGoogleCommonCollectMinMaxPriorityQueue_getMaxElementIndex(ComGoogleCommonCollectMinMaxPriorityQueue *self);

__attribute__((unused)) static ComGoogleCommonCollectMinMaxPriorityQueue_MoveDesc *ComGoogleCommonCollectMinMaxPriorityQueue_fillHoleWithInt_withId_(ComGoogleCommonCollectMinMaxPriorityQueue *self, jint index, id toTrickle);

__attribute__((unused)) static id ComGoogleCommonCollectMinMaxPriorityQueue_removeAndGetWithInt_(ComGoogleCommonCollectMinMaxPriorityQueue *self, jint index);

__attribute__((unused)) static ComGoogleCommonCollectMinMaxPriorityQueue_Heap *ComGoogleCommonCollectMinMaxPriorityQueue_heapForIndexWithInt_(ComGoogleCommonCollectMinMaxPriorityQueue *self, jint i);

__attribute__((unused)) static void ComGoogleCommonCollectMinMaxPriorityQueue_growIfNeeded(ComGoogleCommonCollectMinMaxPriorityQueue *self);

__attribute__((unused)) static jint ComGoogleCommonCollectMinMaxPriorityQueue_calculateNewCapacity(ComGoogleCommonCollectMinMaxPriorityQueue *self);

__attribute__((unused)) static jint ComGoogleCommonCollectMinMaxPriorityQueue_capAtMaximumSizeWithInt_withInt_(jint queueSize, jint maximumSize);

@interface ComGoogleCommonCollectMinMaxPriorityQueue_Builder () {
 @public
  id<JavaUtilComparator> comparator_;
  jint expectedSize_;
  jint maximumSize_;
}

- (instancetype)initWithJavaUtilComparator:(id<JavaUtilComparator>)comparator;

- (ComGoogleCommonCollectOrdering *)ordering;

@end

J2OBJC_FIELD_SETTER(ComGoogleCommonCollectMinMaxPriorityQueue_Builder, comparator_, id<JavaUtilComparator>)

inline jint ComGoogleCommonCollectMinMaxPriorityQueue_Builder_get_UNSET_EXPECTED_SIZE();
#define ComGoogleCommonCollectMinMaxPriorityQueue_Builder_UNSET_EXPECTED_SIZE -1
J2OBJC_STATIC_FIELD_CONSTANT(ComGoogleCommonCollectMinMaxPriorityQueue_Builder, UNSET_EXPECTED_SIZE, jint)

__attribute__((unused)) static void ComGoogleCommonCollectMinMaxPriorityQueue_Builder_initWithJavaUtilComparator_(ComGoogleCommonCollectMinMaxPriorityQueue_Builder *self, id<JavaUtilComparator> comparator);

__attribute__((unused)) static ComGoogleCommonCollectMinMaxPriorityQueue_Builder *new_ComGoogleCommonCollectMinMaxPriorityQueue_Builder_initWithJavaUtilComparator_(id<JavaUtilComparator> comparator) NS_RETURNS_RETAINED;

__attribute__((unused)) static ComGoogleCommonCollectMinMaxPriorityQueue_Builder *create_ComGoogleCommonCollectMinMaxPriorityQueue_Builder_initWithJavaUtilComparator_(id<JavaUtilComparator> comparator);

__attribute__((unused)) static ComGoogleCommonCollectOrdering *ComGoogleCommonCollectMinMaxPriorityQueue_Builder_ordering(ComGoogleCommonCollectMinMaxPriorityQueue_Builder *self);

@interface ComGoogleCommonCollectMinMaxPriorityQueue_Heap : NSObject {
 @public
  __unsafe_unretained ComGoogleCommonCollectMinMaxPriorityQueue *this$0_;
  ComGoogleCommonCollectOrdering *ordering_;
  __unsafe_unretained ComGoogleCommonCollectMinMaxPriorityQueue_Heap *otherHeap_;
}

- (instancetype)initWithComGoogleCommonCollectMinMaxPriorityQueue:(ComGoogleCommonCollectMinMaxPriorityQueue *)outer$
                               withComGoogleCommonCollectOrdering:(ComGoogleCommonCollectOrdering *)ordering;

- (jint)compareElementsWithInt:(jint)a
                       withInt:(jint)b;

- (ComGoogleCommonCollectMinMaxPriorityQueue_MoveDesc *)tryCrossOverAndBubbleUpWithInt:(jint)removeIndex
                                                                               withInt:(jint)vacated
                                                                                withId:(id)toTrickle;

- (void)bubbleUpWithInt:(jint)index
                 withId:(id)x;

- (jint)bubbleUpAlternatingLevelsWithInt:(jint)index
                                  withId:(id)x;

- (jint)findMinWithInt:(jint)index
               withInt:(jint)len;

- (jint)findMinChildWithInt:(jint)index;

- (jint)findMinGrandChildWithInt:(jint)index;

- (jint)crossOverUpWithInt:(jint)index
                    withId:(id)x;

- (jint)swapWithConceptuallyLastElementWithId:(id)actualLastElement;

- (jint)crossOverWithInt:(jint)index
                  withId:(id)x;

- (jint)fillHoleAtWithInt:(jint)index;

- (jboolean)verifyIndexWithInt:(jint)i;

- (jint)getLeftChildIndexWithInt:(jint)i;

- (jint)getRightChildIndexWithInt:(jint)i;

- (jint)getParentIndexWithInt:(jint)i;

- (jint)getGrandparentIndexWithInt:(jint)i;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectMinMaxPriorityQueue_Heap)

J2OBJC_FIELD_SETTER(ComGoogleCommonCollectMinMaxPriorityQueue_Heap, ordering_, ComGoogleCommonCollectOrdering *)

__attribute__((unused)) static void ComGoogleCommonCollectMinMaxPriorityQueue_Heap_initWithComGoogleCommonCollectMinMaxPriorityQueue_withComGoogleCommonCollectOrdering_(ComGoogleCommonCollectMinMaxPriorityQueue_Heap *self, ComGoogleCommonCollectMinMaxPriorityQueue *outer$, ComGoogleCommonCollectOrdering *ordering);

__attribute__((unused)) static ComGoogleCommonCollectMinMaxPriorityQueue_Heap *new_ComGoogleCommonCollectMinMaxPriorityQueue_Heap_initWithComGoogleCommonCollectMinMaxPriorityQueue_withComGoogleCommonCollectOrdering_(ComGoogleCommonCollectMinMaxPriorityQueue *outer$, ComGoogleCommonCollectOrdering *ordering) NS_RETURNS_RETAINED;

__attribute__((unused)) static ComGoogleCommonCollectMinMaxPriorityQueue_Heap *create_ComGoogleCommonCollectMinMaxPriorityQueue_Heap_initWithComGoogleCommonCollectMinMaxPriorityQueue_withComGoogleCommonCollectOrdering_(ComGoogleCommonCollectMinMaxPriorityQueue *outer$, ComGoogleCommonCollectOrdering *ordering);

__attribute__((unused)) static jboolean ComGoogleCommonCollectMinMaxPriorityQueue_Heap_verifyIndexWithInt_(ComGoogleCommonCollectMinMaxPriorityQueue_Heap *self, jint i);

__attribute__((unused)) static jint ComGoogleCommonCollectMinMaxPriorityQueue_Heap_getLeftChildIndexWithInt_(ComGoogleCommonCollectMinMaxPriorityQueue_Heap *self, jint i);

__attribute__((unused)) static jint ComGoogleCommonCollectMinMaxPriorityQueue_Heap_getRightChildIndexWithInt_(ComGoogleCommonCollectMinMaxPriorityQueue_Heap *self, jint i);

__attribute__((unused)) static jint ComGoogleCommonCollectMinMaxPriorityQueue_Heap_getParentIndexWithInt_(ComGoogleCommonCollectMinMaxPriorityQueue_Heap *self, jint i);

__attribute__((unused)) static jint ComGoogleCommonCollectMinMaxPriorityQueue_Heap_getGrandparentIndexWithInt_(ComGoogleCommonCollectMinMaxPriorityQueue_Heap *self, jint i);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectMinMaxPriorityQueue_Heap)

@interface ComGoogleCommonCollectMinMaxPriorityQueue_QueueIterator : NSObject < JavaUtilIterator > {
 @public
  ComGoogleCommonCollectMinMaxPriorityQueue *this$0_;
  jint cursor_;
  jint nextCursor_;
  jint expectedModCount_;
  id<JavaUtilQueue> forgetMeNot_;
  id<JavaUtilList> skipMe_;
  id lastFromForgetMeNot_;
  jboolean canRemove_;
}

- (instancetype)initWithComGoogleCommonCollectMinMaxPriorityQueue:(ComGoogleCommonCollectMinMaxPriorityQueue *)outer$;

- (jboolean)hasNext;

- (id)next;

- (void)remove;

- (jboolean)foundAndRemovedExactReferenceWithJavaLangIterable:(id<JavaLangIterable>)elements
                                                       withId:(id)target;

- (jboolean)removeExactWithId:(id)target;

- (void)checkModCount;

- (void)nextNotInSkipMeWithInt:(jint)c;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectMinMaxPriorityQueue_QueueIterator)

J2OBJC_FIELD_SETTER(ComGoogleCommonCollectMinMaxPriorityQueue_QueueIterator, forgetMeNot_, id<JavaUtilQueue>)
J2OBJC_FIELD_SETTER(ComGoogleCommonCollectMinMaxPriorityQueue_QueueIterator, skipMe_, id<JavaUtilList>)
J2OBJC_FIELD_SETTER(ComGoogleCommonCollectMinMaxPriorityQueue_QueueIterator, lastFromForgetMeNot_, id)

__attribute__((unused)) static void ComGoogleCommonCollectMinMaxPriorityQueue_QueueIterator_initWithComGoogleCommonCollectMinMaxPriorityQueue_(ComGoogleCommonCollectMinMaxPriorityQueue_QueueIterator *self, ComGoogleCommonCollectMinMaxPriorityQueue *outer$);

__attribute__((unused)) static ComGoogleCommonCollectMinMaxPriorityQueue_QueueIterator *new_ComGoogleCommonCollectMinMaxPriorityQueue_QueueIterator_initWithComGoogleCommonCollectMinMaxPriorityQueue_(ComGoogleCommonCollectMinMaxPriorityQueue *outer$) NS_RETURNS_RETAINED;

__attribute__((unused)) static ComGoogleCommonCollectMinMaxPriorityQueue_QueueIterator *create_ComGoogleCommonCollectMinMaxPriorityQueue_QueueIterator_initWithComGoogleCommonCollectMinMaxPriorityQueue_(ComGoogleCommonCollectMinMaxPriorityQueue *outer$);

__attribute__((unused)) static jboolean ComGoogleCommonCollectMinMaxPriorityQueue_QueueIterator_foundAndRemovedExactReferenceWithJavaLangIterable_withId_(ComGoogleCommonCollectMinMaxPriorityQueue_QueueIterator *self, id<JavaLangIterable> elements, id target);

__attribute__((unused)) static jboolean ComGoogleCommonCollectMinMaxPriorityQueue_QueueIterator_removeExactWithId_(ComGoogleCommonCollectMinMaxPriorityQueue_QueueIterator *self, id target);

__attribute__((unused)) static void ComGoogleCommonCollectMinMaxPriorityQueue_QueueIterator_checkModCount(ComGoogleCommonCollectMinMaxPriorityQueue_QueueIterator *self);

__attribute__((unused)) static void ComGoogleCommonCollectMinMaxPriorityQueue_QueueIterator_nextNotInSkipMeWithInt_(ComGoogleCommonCollectMinMaxPriorityQueue_QueueIterator *self, jint c);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectMinMaxPriorityQueue_QueueIterator)

@implementation ComGoogleCommonCollectMinMaxPriorityQueue

+ (ComGoogleCommonCollectMinMaxPriorityQueue *)create {
  return ComGoogleCommonCollectMinMaxPriorityQueue_create();
}

+ (ComGoogleCommonCollectMinMaxPriorityQueue *)createWithJavaLangIterable:(id<JavaLangIterable>)initialContents {
  return ComGoogleCommonCollectMinMaxPriorityQueue_createWithJavaLangIterable_(initialContents);
}

+ (ComGoogleCommonCollectMinMaxPriorityQueue_Builder *)orderedByWithJavaUtilComparator:(id<JavaUtilComparator>)comparator {
  return ComGoogleCommonCollectMinMaxPriorityQueue_orderedByWithJavaUtilComparator_(comparator);
}

+ (ComGoogleCommonCollectMinMaxPriorityQueue_Builder *)expectedSizeWithInt:(jint)expectedSize {
  return ComGoogleCommonCollectMinMaxPriorityQueue_expectedSizeWithInt_(expectedSize);
}

+ (ComGoogleCommonCollectMinMaxPriorityQueue_Builder *)maximumSizeWithInt:(jint)maximumSize {
  return ComGoogleCommonCollectMinMaxPriorityQueue_maximumSizeWithInt_(maximumSize);
}

- (instancetype)initWithComGoogleCommonCollectMinMaxPriorityQueue_Builder:(ComGoogleCommonCollectMinMaxPriorityQueue_Builder *)builder
                                                                  withInt:(jint)queueSize {
  ComGoogleCommonCollectMinMaxPriorityQueue_initWithComGoogleCommonCollectMinMaxPriorityQueue_Builder_withInt_(self, builder, queueSize);
  return self;
}

- (jint)size {
  return size_;
}

- (jboolean)addWithId:(id)element {
  [self offerWithId:element];
  return true;
}

- (jboolean)addAllWithJavaUtilCollection:(id<JavaUtilCollection>)newElements {
  jboolean modified = false;
  for (id __strong element in nil_chk(newElements)) {
    [self offerWithId:element];
    modified = true;
  }
  return modified;
}

- (jboolean)offerWithId:(id)element {
  (void) ComGoogleCommonBasePreconditions_checkNotNullWithId_(element);
  modCount_++;
  jint insertIndex = size_++;
  ComGoogleCommonCollectMinMaxPriorityQueue_growIfNeeded(self);
  [((ComGoogleCommonCollectMinMaxPriorityQueue_Heap *) nil_chk(ComGoogleCommonCollectMinMaxPriorityQueue_heapForIndexWithInt_(self, insertIndex))) bubbleUpWithInt:insertIndex withId:element];
  return size_ <= maximumSize_ || [self pollLast] != element;
}

- (id)poll {
  return [self isEmpty] ? nil : ComGoogleCommonCollectMinMaxPriorityQueue_removeAndGetWithInt_(self, 0);
}

- (id)elementDataWithInt:(jint)index {
  return IOSObjectArray_Get(nil_chk(queue_), index);
}

- (id)peek {
  return [self isEmpty] ? nil : [self elementDataWithInt:0];
}

- (jint)getMaxElementIndex {
  return ComGoogleCommonCollectMinMaxPriorityQueue_getMaxElementIndex(self);
}

- (id)pollFirst {
  return [self poll];
}

- (id)removeFirst {
  return [self remove];
}

- (id)peekFirst {
  return [self peek];
}

- (id)pollLast {
  return [self isEmpty] ? nil : ComGoogleCommonCollectMinMaxPriorityQueue_removeAndGetWithInt_(self, ComGoogleCommonCollectMinMaxPriorityQueue_getMaxElementIndex(self));
}

- (id)removeLast {
  if ([self isEmpty]) {
    @throw new_JavaUtilNoSuchElementException_init();
  }
  return ComGoogleCommonCollectMinMaxPriorityQueue_removeAndGetWithInt_(self, ComGoogleCommonCollectMinMaxPriorityQueue_getMaxElementIndex(self));
}

- (id)peekLast {
  return [self isEmpty] ? nil : [self elementDataWithInt:ComGoogleCommonCollectMinMaxPriorityQueue_getMaxElementIndex(self)];
}

- (ComGoogleCommonCollectMinMaxPriorityQueue_MoveDesc *)removeAtWithInt:(jint)index {
  ComGoogleCommonBasePreconditions_checkPositionIndexWithInt_withInt_(index, size_);
  modCount_++;
  size_--;
  if (size_ == index) {
    (void) IOSObjectArray_Set(nil_chk(queue_), size_, nil);
    return nil;
  }
  id actualLastElement = [self elementDataWithInt:size_];
  jint lastElementAt = [((ComGoogleCommonCollectMinMaxPriorityQueue_Heap *) nil_chk(ComGoogleCommonCollectMinMaxPriorityQueue_heapForIndexWithInt_(self, size_))) swapWithConceptuallyLastElementWithId:actualLastElement];
  if (lastElementAt == index) {
    (void) IOSObjectArray_Set(nil_chk(queue_), size_, nil);
    return nil;
  }
  id toTrickle = [self elementDataWithInt:size_];
  (void) IOSObjectArray_Set(nil_chk(queue_), size_, nil);
  ComGoogleCommonCollectMinMaxPriorityQueue_MoveDesc *changes = ComGoogleCommonCollectMinMaxPriorityQueue_fillHoleWithInt_withId_(self, index, toTrickle);
  if (lastElementAt < index) {
    if (changes == nil) {
      return new_ComGoogleCommonCollectMinMaxPriorityQueue_MoveDesc_initWithId_withId_(actualLastElement, toTrickle);
    }
    else {
      return new_ComGoogleCommonCollectMinMaxPriorityQueue_MoveDesc_initWithId_withId_(actualLastElement, changes->replaced_);
    }
  }
  return changes;
}

- (ComGoogleCommonCollectMinMaxPriorityQueue_MoveDesc *)fillHoleWithInt:(jint)index
                                                                 withId:(id)toTrickle {
  return ComGoogleCommonCollectMinMaxPriorityQueue_fillHoleWithInt_withId_(self, index, toTrickle);
}

- (id)removeAndGetWithInt:(jint)index {
  return ComGoogleCommonCollectMinMaxPriorityQueue_removeAndGetWithInt_(self, index);
}

- (ComGoogleCommonCollectMinMaxPriorityQueue_Heap *)heapForIndexWithInt:(jint)i {
  return ComGoogleCommonCollectMinMaxPriorityQueue_heapForIndexWithInt_(self, i);
}

+ (jboolean)isEvenLevelWithInt:(jint)index {
  return ComGoogleCommonCollectMinMaxPriorityQueue_isEvenLevelWithInt_(index);
}

- (jboolean)isIntact {
  for (jint i = 1; i < size_; i++) {
    if (!ComGoogleCommonCollectMinMaxPriorityQueue_Heap_verifyIndexWithInt_(nil_chk(ComGoogleCommonCollectMinMaxPriorityQueue_heapForIndexWithInt_(self, i)), i)) {
      return false;
    }
  }
  return true;
}

- (id<JavaUtilIterator>)iterator {
  return new_ComGoogleCommonCollectMinMaxPriorityQueue_QueueIterator_initWithComGoogleCommonCollectMinMaxPriorityQueue_(self);
}

- (void)clear {
  for (jint i = 0; i < size_; i++) {
    (void) IOSObjectArray_Set(nil_chk(queue_), i, nil);
  }
  size_ = 0;
}

- (IOSObjectArray *)toArray {
  IOSObjectArray *copyTo = [IOSObjectArray newArrayWithLength:size_ type:NSObject_class_()];
  JavaLangSystem_arraycopyWithId_withInt_withId_withInt_withInt_(queue_, 0, copyTo, 0, size_);
  return copyTo;
}

- (id<JavaUtilComparator>)comparator {
  return ((ComGoogleCommonCollectMinMaxPriorityQueue_Heap *) nil_chk(minHeap_))->ordering_;
}

- (jint)capacity {
  return ((IOSObjectArray *) nil_chk(queue_))->size_;
}

+ (jint)initialQueueSizeWithInt:(jint)configuredExpectedSize
                        withInt:(jint)maximumSize
           withJavaLangIterable:(id<JavaLangIterable>)initialContents {
  return ComGoogleCommonCollectMinMaxPriorityQueue_initialQueueSizeWithInt_withInt_withJavaLangIterable_(configuredExpectedSize, maximumSize, initialContents);
}

- (void)growIfNeeded {
  ComGoogleCommonCollectMinMaxPriorityQueue_growIfNeeded(self);
}

- (jint)calculateNewCapacity {
  return ComGoogleCommonCollectMinMaxPriorityQueue_calculateNewCapacity(self);
}

+ (jint)capAtMaximumSizeWithInt:(jint)queueSize
                        withInt:(jint)maximumSize {
  return ComGoogleCommonCollectMinMaxPriorityQueue_capAtMaximumSizeWithInt_withInt_(queueSize, maximumSize);
}

- (NSUInteger)countByEnumeratingWithState:(NSFastEnumerationState *)state objects:(__unsafe_unretained id *)stackbuf count:(NSUInteger)len {
  return JreDefaultFastEnumeration(self, state, stackbuf, len);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "LComGoogleCommonCollectMinMaxPriorityQueue;", 0x9, -1, -1, -1, 0, -1, -1 },
    { NULL, "LComGoogleCommonCollectMinMaxPriorityQueue;", 0x9, 1, 2, -1, 3, -1, -1 },
    { NULL, "LComGoogleCommonCollectMinMaxPriorityQueue_Builder;", 0x9, 4, 5, -1, 6, -1, -1 },
    { NULL, "LComGoogleCommonCollectMinMaxPriorityQueue_Builder;", 0x9, 7, 8, -1, 9, -1, -1 },
    { NULL, "LComGoogleCommonCollectMinMaxPriorityQueue_Builder;", 0x9, 10, 8, -1, 9, -1, -1 },
    { NULL, NULL, 0x2, -1, 11, -1, 12, -1, -1 },
    { NULL, "I", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "Z", 0x1, 13, 14, -1, 15, -1, -1 },
    { NULL, "Z", 0x1, 16, 17, -1, 18, -1, -1 },
    { NULL, "Z", 0x1, 19, 14, -1, 15, -1, -1 },
    { NULL, "LNSObject;", 0x1, -1, -1, -1, 20, -1, -1 },
    { NULL, "LNSObject;", 0x0, 21, 8, -1, 22, -1, -1 },
    { NULL, "LNSObject;", 0x1, -1, -1, -1, 20, -1, -1 },
    { NULL, "I", 0x2, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, -1, -1, -1, 20, -1, -1 },
    { NULL, "LNSObject;", 0x1, -1, -1, -1, 20, -1, -1 },
    { NULL, "LNSObject;", 0x1, -1, -1, -1, 20, -1, -1 },
    { NULL, "LNSObject;", 0x1, -1, -1, -1, 20, -1, -1 },
    { NULL, "LNSObject;", 0x1, -1, -1, -1, 20, -1, -1 },
    { NULL, "LNSObject;", 0x1, -1, -1, -1, 20, -1, -1 },
    { NULL, "LComGoogleCommonCollectMinMaxPriorityQueue_MoveDesc;", 0x0, 23, 8, -1, 24, -1, -1 },
    { NULL, "LComGoogleCommonCollectMinMaxPriorityQueue_MoveDesc;", 0x2, 25, 26, -1, 27, -1, -1 },
    { NULL, "LNSObject;", 0x2, 28, 8, -1, 22, -1, -1 },
    { NULL, "LComGoogleCommonCollectMinMaxPriorityQueue_Heap;", 0x2, 29, 8, -1, -1, -1, -1 },
    { NULL, "Z", 0x8, 30, 8, -1, -1, -1, -1 },
    { NULL, "Z", 0x0, -1, -1, -1, -1, -1, -1 },
    { NULL, "LJavaUtilIterator;", 0x1, -1, -1, -1, 31, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "[LNSObject;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LJavaUtilComparator;", 0x1, -1, -1, -1, 32, -1, -1 },
    { NULL, "I", 0x0, -1, -1, -1, -1, -1, -1 },
    { NULL, "I", 0x8, 33, 34, -1, 35, -1, -1 },
    { NULL, "V", 0x2, -1, -1, -1, -1, -1, -1 },
    { NULL, "I", 0x2, -1, -1, -1, -1, -1, -1 },
    { NULL, "I", 0xa, 36, 37, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(create);
  methods[1].selector = @selector(createWithJavaLangIterable:);
  methods[2].selector = @selector(orderedByWithJavaUtilComparator:);
  methods[3].selector = @selector(expectedSizeWithInt:);
  methods[4].selector = @selector(maximumSizeWithInt:);
  methods[5].selector = @selector(initWithComGoogleCommonCollectMinMaxPriorityQueue_Builder:withInt:);
  methods[6].selector = @selector(size);
  methods[7].selector = @selector(addWithId:);
  methods[8].selector = @selector(addAllWithJavaUtilCollection:);
  methods[9].selector = @selector(offerWithId:);
  methods[10].selector = @selector(poll);
  methods[11].selector = @selector(elementDataWithInt:);
  methods[12].selector = @selector(peek);
  methods[13].selector = @selector(getMaxElementIndex);
  methods[14].selector = @selector(pollFirst);
  methods[15].selector = @selector(removeFirst);
  methods[16].selector = @selector(peekFirst);
  methods[17].selector = @selector(pollLast);
  methods[18].selector = @selector(removeLast);
  methods[19].selector = @selector(peekLast);
  methods[20].selector = @selector(removeAtWithInt:);
  methods[21].selector = @selector(fillHoleWithInt:withId:);
  methods[22].selector = @selector(removeAndGetWithInt:);
  methods[23].selector = @selector(heapForIndexWithInt:);
  methods[24].selector = @selector(isEvenLevelWithInt:);
  methods[25].selector = @selector(isIntact);
  methods[26].selector = @selector(iterator);
  methods[27].selector = @selector(clear);
  methods[28].selector = @selector(toArray);
  methods[29].selector = @selector(comparator);
  methods[30].selector = @selector(capacity);
  methods[31].selector = @selector(initialQueueSizeWithInt:withInt:withJavaLangIterable:);
  methods[32].selector = @selector(growIfNeeded);
  methods[33].selector = @selector(calculateNewCapacity);
  methods[34].selector = @selector(capAtMaximumSizeWithInt:withInt:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "minHeap_", "LComGoogleCommonCollectMinMaxPriorityQueue_Heap;", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
    { "maxHeap_", "LComGoogleCommonCollectMinMaxPriorityQueue_Heap;", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
    { "maximumSize_", "I", .constantValue.asLong = 0, 0x10, -1, -1, -1, -1 },
    { "queue_", "[LNSObject;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "size_", "I", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "modCount_", "I", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "EVEN_POWERS_OF_TWO", "I", .constantValue.asInt = ComGoogleCommonCollectMinMaxPriorityQueue_EVEN_POWERS_OF_TWO, 0x1a, -1, -1, -1, -1 },
    { "ODD_POWERS_OF_TWO", "I", .constantValue.asInt = ComGoogleCommonCollectMinMaxPriorityQueue_ODD_POWERS_OF_TWO, 0x1a, -1, -1, -1, -1 },
    { "DEFAULT_CAPACITY", "I", .constantValue.asInt = ComGoogleCommonCollectMinMaxPriorityQueue_DEFAULT_CAPACITY, 0x1a, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "<E::Ljava/lang/Comparable<TE;>;>()Lcom/google/common/collect/MinMaxPriorityQueue<TE;>;", "create", "LJavaLangIterable;", "<E::Ljava/lang/Comparable<TE;>;>(Ljava/lang/Iterable<+TE;>;)Lcom/google/common/collect/MinMaxPriorityQueue<TE;>;", "orderedBy", "LJavaUtilComparator;", "<B:Ljava/lang/Object;>(Ljava/util/Comparator<TB;>;)Lcom/google/common/collect/MinMaxPriorityQueue$Builder<TB;>;", "expectedSize", "I", "(I)Lcom/google/common/collect/MinMaxPriorityQueue$Builder<Ljava/lang/Comparable;>;", "maximumSize", "LComGoogleCommonCollectMinMaxPriorityQueue_Builder;I", "(Lcom/google/common/collect/MinMaxPriorityQueue$Builder<-TE;>;I)V", "add", "LNSObject;", "(TE;)Z", "addAll", "LJavaUtilCollection;", "(Ljava/util/Collection<+TE;>;)Z", "offer", "()TE;", "elementData", "(I)TE;", "removeAt", "(I)Lcom/google/common/collect/MinMaxPriorityQueue$MoveDesc<TE;>;", "fillHole", "ILNSObject;", "(ITE;)Lcom/google/common/collect/MinMaxPriorityQueue$MoveDesc<TE;>;", "removeAndGet", "heapForIndex", "isEvenLevel", "()Ljava/util/Iterator<TE;>;", "()Ljava/util/Comparator<-TE;>;", "initialQueueSize", "IILJavaLangIterable;", "(IILjava/lang/Iterable<*>;)I", "capAtMaximumSize", "II", "LComGoogleCommonCollectMinMaxPriorityQueue_Builder;LComGoogleCommonCollectMinMaxPriorityQueue_MoveDesc;LComGoogleCommonCollectMinMaxPriorityQueue_Heap;LComGoogleCommonCollectMinMaxPriorityQueue_QueueIterator;", "<E:Ljava/lang/Object;>Ljava/util/AbstractQueue<TE;>;" };
  static const J2ObjcClassInfo _ComGoogleCommonCollectMinMaxPriorityQueue = { "MinMaxPriorityQueue", "com.google.common.collect", ptrTable, methods, fields, 7, 0x11, 35, 9, -1, 38, -1, 39, -1 };
  return &_ComGoogleCommonCollectMinMaxPriorityQueue;
}

@end

ComGoogleCommonCollectMinMaxPriorityQueue *ComGoogleCommonCollectMinMaxPriorityQueue_create() {
  ComGoogleCommonCollectMinMaxPriorityQueue_initialize();
  return [new_ComGoogleCommonCollectMinMaxPriorityQueue_Builder_initWithJavaUtilComparator_(ComGoogleCommonCollectOrdering_natural()) create];
}

ComGoogleCommonCollectMinMaxPriorityQueue *ComGoogleCommonCollectMinMaxPriorityQueue_createWithJavaLangIterable_(id<JavaLangIterable> initialContents) {
  ComGoogleCommonCollectMinMaxPriorityQueue_initialize();
  return [new_ComGoogleCommonCollectMinMaxPriorityQueue_Builder_initWithJavaUtilComparator_(ComGoogleCommonCollectOrdering_natural()) createWithJavaLangIterable:initialContents];
}

ComGoogleCommonCollectMinMaxPriorityQueue_Builder *ComGoogleCommonCollectMinMaxPriorityQueue_orderedByWithJavaUtilComparator_(id<JavaUtilComparator> comparator) {
  ComGoogleCommonCollectMinMaxPriorityQueue_initialize();
  return new_ComGoogleCommonCollectMinMaxPriorityQueue_Builder_initWithJavaUtilComparator_(comparator);
}

ComGoogleCommonCollectMinMaxPriorityQueue_Builder *ComGoogleCommonCollectMinMaxPriorityQueue_expectedSizeWithInt_(jint expectedSize) {
  ComGoogleCommonCollectMinMaxPriorityQueue_initialize();
  return [new_ComGoogleCommonCollectMinMaxPriorityQueue_Builder_initWithJavaUtilComparator_(ComGoogleCommonCollectOrdering_natural()) expectedSizeWithInt:expectedSize];
}

ComGoogleCommonCollectMinMaxPriorityQueue_Builder *ComGoogleCommonCollectMinMaxPriorityQueue_maximumSizeWithInt_(jint maximumSize) {
  ComGoogleCommonCollectMinMaxPriorityQueue_initialize();
  return [new_ComGoogleCommonCollectMinMaxPriorityQueue_Builder_initWithJavaUtilComparator_(ComGoogleCommonCollectOrdering_natural()) maximumSizeWithInt:maximumSize];
}

void ComGoogleCommonCollectMinMaxPriorityQueue_initWithComGoogleCommonCollectMinMaxPriorityQueue_Builder_withInt_(ComGoogleCommonCollectMinMaxPriorityQueue *self, ComGoogleCommonCollectMinMaxPriorityQueue_Builder *builder, jint queueSize) {
  JavaUtilAbstractQueue_init(self);
  ComGoogleCommonCollectOrdering *ordering = ComGoogleCommonCollectMinMaxPriorityQueue_Builder_ordering(nil_chk(builder));
  self->minHeap_ = new_ComGoogleCommonCollectMinMaxPriorityQueue_Heap_initWithComGoogleCommonCollectMinMaxPriorityQueue_withComGoogleCommonCollectOrdering_(self, ordering);
  self->maxHeap_ = new_ComGoogleCommonCollectMinMaxPriorityQueue_Heap_initWithComGoogleCommonCollectMinMaxPriorityQueue_withComGoogleCommonCollectOrdering_(self, [((ComGoogleCommonCollectOrdering *) nil_chk(ordering)) reverse]);
  self->minHeap_->otherHeap_ = self->maxHeap_;
  self->maxHeap_->otherHeap_ = self->minHeap_;
  self->maximumSize_ = builder->maximumSize_;
  self->queue_ = [IOSObjectArray newArrayWithLength:queueSize type:NSObject_class_()];
}

ComGoogleCommonCollectMinMaxPriorityQueue *new_ComGoogleCommonCollectMinMaxPriorityQueue_initWithComGoogleCommonCollectMinMaxPriorityQueue_Builder_withInt_(ComGoogleCommonCollectMinMaxPriorityQueue_Builder *builder, jint queueSize) {
  J2OBJC_NEW_IMPL(ComGoogleCommonCollectMinMaxPriorityQueue, initWithComGoogleCommonCollectMinMaxPriorityQueue_Builder_withInt_, builder, queueSize)
}

ComGoogleCommonCollectMinMaxPriorityQueue *create_ComGoogleCommonCollectMinMaxPriorityQueue_initWithComGoogleCommonCollectMinMaxPriorityQueue_Builder_withInt_(ComGoogleCommonCollectMinMaxPriorityQueue_Builder *builder, jint queueSize) {
  J2OBJC_CREATE_IMPL(ComGoogleCommonCollectMinMaxPriorityQueue, initWithComGoogleCommonCollectMinMaxPriorityQueue_Builder_withInt_, builder, queueSize)
}

jint ComGoogleCommonCollectMinMaxPriorityQueue_getMaxElementIndex(ComGoogleCommonCollectMinMaxPriorityQueue *self) {
  switch (self->size_) {
    case 1:
    return 0;
    case 2:
    return 1;
    default:
    return ([((ComGoogleCommonCollectMinMaxPriorityQueue_Heap *) nil_chk(self->maxHeap_)) compareElementsWithInt:1 withInt:2] <= 0) ? 1 : 2;
  }
}

ComGoogleCommonCollectMinMaxPriorityQueue_MoveDesc *ComGoogleCommonCollectMinMaxPriorityQueue_fillHoleWithInt_withId_(ComGoogleCommonCollectMinMaxPriorityQueue *self, jint index, id toTrickle) {
  ComGoogleCommonCollectMinMaxPriorityQueue_Heap *heap = ComGoogleCommonCollectMinMaxPriorityQueue_heapForIndexWithInt_(self, index);
  jint vacated = [((ComGoogleCommonCollectMinMaxPriorityQueue_Heap *) nil_chk(heap)) fillHoleAtWithInt:index];
  jint bubbledTo = [heap bubbleUpAlternatingLevelsWithInt:vacated withId:toTrickle];
  if (bubbledTo == vacated) {
    return [heap tryCrossOverAndBubbleUpWithInt:index withInt:vacated withId:toTrickle];
  }
  else {
    return (bubbledTo < index) ? new_ComGoogleCommonCollectMinMaxPriorityQueue_MoveDesc_initWithId_withId_(toTrickle, [self elementDataWithInt:index]) : nil;
  }
}

id ComGoogleCommonCollectMinMaxPriorityQueue_removeAndGetWithInt_(ComGoogleCommonCollectMinMaxPriorityQueue *self, jint index) {
  id value = [self elementDataWithInt:index];
  (void) [self removeAtWithInt:index];
  return value;
}

ComGoogleCommonCollectMinMaxPriorityQueue_Heap *ComGoogleCommonCollectMinMaxPriorityQueue_heapForIndexWithInt_(ComGoogleCommonCollectMinMaxPriorityQueue *self, jint i) {
  return ComGoogleCommonCollectMinMaxPriorityQueue_isEvenLevelWithInt_(i) ? self->minHeap_ : self->maxHeap_;
}

jboolean ComGoogleCommonCollectMinMaxPriorityQueue_isEvenLevelWithInt_(jint index) {
  ComGoogleCommonCollectMinMaxPriorityQueue_initialize();
  jint oneBased = ~(~(index + 1));
  ComGoogleCommonBasePreconditions_checkStateWithBoolean_withId_(oneBased > 0, @"negative index");
  return (oneBased & ComGoogleCommonCollectMinMaxPriorityQueue_EVEN_POWERS_OF_TWO) > (oneBased & ComGoogleCommonCollectMinMaxPriorityQueue_ODD_POWERS_OF_TWO);
}

jint ComGoogleCommonCollectMinMaxPriorityQueue_initialQueueSizeWithInt_withInt_withJavaLangIterable_(jint configuredExpectedSize, jint maximumSize, id<JavaLangIterable> initialContents) {
  ComGoogleCommonCollectMinMaxPriorityQueue_initialize();
  jint result = (configuredExpectedSize == ComGoogleCommonCollectMinMaxPriorityQueue_Builder_UNSET_EXPECTED_SIZE) ? ComGoogleCommonCollectMinMaxPriorityQueue_DEFAULT_CAPACITY : configuredExpectedSize;
  if ([JavaUtilCollection_class_() isInstance:initialContents]) {
    jint initialSize = [((id<JavaUtilCollection>) nil_chk(((id<JavaUtilCollection>) cast_check(initialContents, JavaUtilCollection_class_())))) size];
    result = JavaLangMath_maxWithInt_withInt_(result, initialSize);
  }
  return ComGoogleCommonCollectMinMaxPriorityQueue_capAtMaximumSizeWithInt_withInt_(result, maximumSize);
}

void ComGoogleCommonCollectMinMaxPriorityQueue_growIfNeeded(ComGoogleCommonCollectMinMaxPriorityQueue *self) {
  if (self->size_ > ((IOSObjectArray *) nil_chk(self->queue_))->size_) {
    jint newCapacity = ComGoogleCommonCollectMinMaxPriorityQueue_calculateNewCapacity(self);
    IOSObjectArray *newQueue = [IOSObjectArray newArrayWithLength:newCapacity type:NSObject_class_()];
    JavaLangSystem_arraycopyWithId_withInt_withId_withInt_withInt_(self->queue_, 0, newQueue, 0, ((IOSObjectArray *) nil_chk(self->queue_))->size_);
    self->queue_ = newQueue;
  }
}

jint ComGoogleCommonCollectMinMaxPriorityQueue_calculateNewCapacity(ComGoogleCommonCollectMinMaxPriorityQueue *self) {
  jint oldCapacity = ((IOSObjectArray *) nil_chk(self->queue_))->size_;
  jint newCapacity = (oldCapacity < 64) ? (oldCapacity + 1) * 2 : ComGoogleCommonMathIntMath_checkedMultiplyWithInt_withInt_(oldCapacity / 2, 3);
  return ComGoogleCommonCollectMinMaxPriorityQueue_capAtMaximumSizeWithInt_withInt_(newCapacity, self->maximumSize_);
}

jint ComGoogleCommonCollectMinMaxPriorityQueue_capAtMaximumSizeWithInt_withInt_(jint queueSize, jint maximumSize) {
  ComGoogleCommonCollectMinMaxPriorityQueue_initialize();
  return JavaLangMath_minWithInt_withInt_(queueSize - 1, maximumSize) + 1;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComGoogleCommonCollectMinMaxPriorityQueue)

@implementation ComGoogleCommonCollectMinMaxPriorityQueue_Builder

- (instancetype)initWithJavaUtilComparator:(id<JavaUtilComparator>)comparator {
  ComGoogleCommonCollectMinMaxPriorityQueue_Builder_initWithJavaUtilComparator_(self, comparator);
  return self;
}

- (ComGoogleCommonCollectMinMaxPriorityQueue_Builder *)expectedSizeWithInt:(jint)expectedSize {
  ComGoogleCommonBasePreconditions_checkArgumentWithBoolean_(expectedSize >= 0);
  self->expectedSize_ = expectedSize;
  return self;
}

- (ComGoogleCommonCollectMinMaxPriorityQueue_Builder *)maximumSizeWithInt:(jint)maximumSize {
  ComGoogleCommonBasePreconditions_checkArgumentWithBoolean_(maximumSize > 0);
  self->maximumSize_ = maximumSize;
  return self;
}

- (ComGoogleCommonCollectMinMaxPriorityQueue *)create {
  return [self createWithJavaLangIterable:JavaUtilCollections_emptySet()];
}

- (ComGoogleCommonCollectMinMaxPriorityQueue *)createWithJavaLangIterable:(id<JavaLangIterable>)initialContents {
  ComGoogleCommonCollectMinMaxPriorityQueue *queue = new_ComGoogleCommonCollectMinMaxPriorityQueue_initWithComGoogleCommonCollectMinMaxPriorityQueue_Builder_withInt_(self, ComGoogleCommonCollectMinMaxPriorityQueue_initialQueueSizeWithInt_withInt_withJavaLangIterable_(expectedSize_, maximumSize_, initialContents));
  for (id __strong element in nil_chk(initialContents)) {
    [queue offerWithId:element];
  }
  return queue;
}

- (ComGoogleCommonCollectOrdering *)ordering {
  return ComGoogleCommonCollectMinMaxPriorityQueue_Builder_ordering(self);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x2, -1, 0, -1, 1, -1, -1 },
    { NULL, "LComGoogleCommonCollectMinMaxPriorityQueue_Builder;", 0x1, 2, 3, -1, 4, -1, -1 },
    { NULL, "LComGoogleCommonCollectMinMaxPriorityQueue_Builder;", 0x1, 5, 3, -1, 4, -1, -1 },
    { NULL, "LComGoogleCommonCollectMinMaxPriorityQueue;", 0x1, -1, -1, -1, 6, -1, -1 },
    { NULL, "LComGoogleCommonCollectMinMaxPriorityQueue;", 0x1, 7, 8, -1, 9, -1, -1 },
    { NULL, "LComGoogleCommonCollectOrdering;", 0x2, -1, -1, -1, 10, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(initWithJavaUtilComparator:);
  methods[1].selector = @selector(expectedSizeWithInt:);
  methods[2].selector = @selector(maximumSizeWithInt:);
  methods[3].selector = @selector(create);
  methods[4].selector = @selector(createWithJavaLangIterable:);
  methods[5].selector = @selector(ordering);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "UNSET_EXPECTED_SIZE", "I", .constantValue.asInt = ComGoogleCommonCollectMinMaxPriorityQueue_Builder_UNSET_EXPECTED_SIZE, 0x1a, -1, -1, -1, -1 },
    { "comparator_", "LJavaUtilComparator;", .constantValue.asLong = 0, 0x12, -1, -1, 11, -1 },
    { "expectedSize_", "I", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "maximumSize_", "I", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LJavaUtilComparator;", "(Ljava/util/Comparator<TB;>;)V", "expectedSize", "I", "(I)Lcom/google/common/collect/MinMaxPriorityQueue$Builder<TB;>;", "maximumSize", "<T:TB;>()Lcom/google/common/collect/MinMaxPriorityQueue<TT;>;", "create", "LJavaLangIterable;", "<T:TB;>(Ljava/lang/Iterable<+TT;>;)Lcom/google/common/collect/MinMaxPriorityQueue<TT;>;", "<T:TB;>()Lcom/google/common/collect/Ordering<TT;>;", "Ljava/util/Comparator<TB;>;", "LComGoogleCommonCollectMinMaxPriorityQueue;", "<B:Ljava/lang/Object;>Ljava/lang/Object;" };
  static const J2ObjcClassInfo _ComGoogleCommonCollectMinMaxPriorityQueue_Builder = { "Builder", "com.google.common.collect", ptrTable, methods, fields, 7, 0x19, 6, 4, 12, -1, -1, 13, -1 };
  return &_ComGoogleCommonCollectMinMaxPriorityQueue_Builder;
}

@end

void ComGoogleCommonCollectMinMaxPriorityQueue_Builder_initWithJavaUtilComparator_(ComGoogleCommonCollectMinMaxPriorityQueue_Builder *self, id<JavaUtilComparator> comparator) {
  NSObject_init(self);
  self->expectedSize_ = ComGoogleCommonCollectMinMaxPriorityQueue_Builder_UNSET_EXPECTED_SIZE;
  self->maximumSize_ = JavaLangInteger_MAX_VALUE;
  self->comparator_ = ComGoogleCommonBasePreconditions_checkNotNullWithId_(comparator);
}

ComGoogleCommonCollectMinMaxPriorityQueue_Builder *new_ComGoogleCommonCollectMinMaxPriorityQueue_Builder_initWithJavaUtilComparator_(id<JavaUtilComparator> comparator) {
  J2OBJC_NEW_IMPL(ComGoogleCommonCollectMinMaxPriorityQueue_Builder, initWithJavaUtilComparator_, comparator)
}

ComGoogleCommonCollectMinMaxPriorityQueue_Builder *create_ComGoogleCommonCollectMinMaxPriorityQueue_Builder_initWithJavaUtilComparator_(id<JavaUtilComparator> comparator) {
  J2OBJC_CREATE_IMPL(ComGoogleCommonCollectMinMaxPriorityQueue_Builder, initWithJavaUtilComparator_, comparator)
}

ComGoogleCommonCollectOrdering *ComGoogleCommonCollectMinMaxPriorityQueue_Builder_ordering(ComGoogleCommonCollectMinMaxPriorityQueue_Builder *self) {
  return ComGoogleCommonCollectOrdering_fromWithJavaUtilComparator_(self->comparator_);
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComGoogleCommonCollectMinMaxPriorityQueue_Builder)

@implementation ComGoogleCommonCollectMinMaxPriorityQueue_MoveDesc

- (instancetype)initWithId:(id)toTrickle
                    withId:(id)replaced {
  ComGoogleCommonCollectMinMaxPriorityQueue_MoveDesc_initWithId_withId_(self, toTrickle, replaced);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x0, -1, 0, -1, 1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(initWithId:withId:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "toTrickle_", "LNSObject;", .constantValue.asLong = 0, 0x10, -1, -1, 2, -1 },
    { "replaced_", "LNSObject;", .constantValue.asLong = 0, 0x10, -1, -1, 2, -1 },
  };
  static const void *ptrTable[] = { "LNSObject;LNSObject;", "(TE;TE;)V", "TE;", "LComGoogleCommonCollectMinMaxPriorityQueue;", "<E:Ljava/lang/Object;>Ljava/lang/Object;" };
  static const J2ObjcClassInfo _ComGoogleCommonCollectMinMaxPriorityQueue_MoveDesc = { "MoveDesc", "com.google.common.collect", ptrTable, methods, fields, 7, 0x8, 1, 2, 3, -1, -1, 4, -1 };
  return &_ComGoogleCommonCollectMinMaxPriorityQueue_MoveDesc;
}

@end

void ComGoogleCommonCollectMinMaxPriorityQueue_MoveDesc_initWithId_withId_(ComGoogleCommonCollectMinMaxPriorityQueue_MoveDesc *self, id toTrickle, id replaced) {
  NSObject_init(self);
  self->toTrickle_ = toTrickle;
  self->replaced_ = replaced;
}

ComGoogleCommonCollectMinMaxPriorityQueue_MoveDesc *new_ComGoogleCommonCollectMinMaxPriorityQueue_MoveDesc_initWithId_withId_(id toTrickle, id replaced) {
  J2OBJC_NEW_IMPL(ComGoogleCommonCollectMinMaxPriorityQueue_MoveDesc, initWithId_withId_, toTrickle, replaced)
}

ComGoogleCommonCollectMinMaxPriorityQueue_MoveDesc *create_ComGoogleCommonCollectMinMaxPriorityQueue_MoveDesc_initWithId_withId_(id toTrickle, id replaced) {
  J2OBJC_CREATE_IMPL(ComGoogleCommonCollectMinMaxPriorityQueue_MoveDesc, initWithId_withId_, toTrickle, replaced)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComGoogleCommonCollectMinMaxPriorityQueue_MoveDesc)

@implementation ComGoogleCommonCollectMinMaxPriorityQueue_Heap

- (instancetype)initWithComGoogleCommonCollectMinMaxPriorityQueue:(ComGoogleCommonCollectMinMaxPriorityQueue *)outer$
                               withComGoogleCommonCollectOrdering:(ComGoogleCommonCollectOrdering *)ordering {
  ComGoogleCommonCollectMinMaxPriorityQueue_Heap_initWithComGoogleCommonCollectMinMaxPriorityQueue_withComGoogleCommonCollectOrdering_(self, outer$, ordering);
  return self;
}

- (jint)compareElementsWithInt:(jint)a
                       withInt:(jint)b {
  return [((ComGoogleCommonCollectOrdering *) nil_chk(ordering_)) compareWithId:[this$0_ elementDataWithInt:a] withId:[this$0_ elementDataWithInt:b]];
}

- (ComGoogleCommonCollectMinMaxPriorityQueue_MoveDesc *)tryCrossOverAndBubbleUpWithInt:(jint)removeIndex
                                                                               withInt:(jint)vacated
                                                                                withId:(id)toTrickle {
  jint crossOver = [self crossOverWithInt:vacated withId:toTrickle];
  if (crossOver == vacated) {
    return nil;
  }
  id parent;
  if (crossOver < removeIndex) {
    parent = [this$0_ elementDataWithInt:removeIndex];
  }
  else {
    parent = [this$0_ elementDataWithInt:ComGoogleCommonCollectMinMaxPriorityQueue_Heap_getParentIndexWithInt_(self, removeIndex)];
  }
  if ([((ComGoogleCommonCollectMinMaxPriorityQueue_Heap *) nil_chk(otherHeap_)) bubbleUpAlternatingLevelsWithInt:crossOver withId:toTrickle] < removeIndex) {
    return new_ComGoogleCommonCollectMinMaxPriorityQueue_MoveDesc_initWithId_withId_(toTrickle, parent);
  }
  else {
    return nil;
  }
}

- (void)bubbleUpWithInt:(jint)index
                 withId:(id)x {
  jint crossOver = [self crossOverUpWithInt:index withId:x];
  ComGoogleCommonCollectMinMaxPriorityQueue_Heap *heap;
  if (crossOver == index) {
    heap = self;
  }
  else {
    index = crossOver;
    heap = otherHeap_;
  }
  [((ComGoogleCommonCollectMinMaxPriorityQueue_Heap *) nil_chk(heap)) bubbleUpAlternatingLevelsWithInt:index withId:x];
}

- (jint)bubbleUpAlternatingLevelsWithInt:(jint)index
                                  withId:(id)x {
  while (index > 2) {
    jint grandParentIndex = ComGoogleCommonCollectMinMaxPriorityQueue_Heap_getGrandparentIndexWithInt_(self, index);
    id e = [this$0_ elementDataWithInt:grandParentIndex];
    if ([((ComGoogleCommonCollectOrdering *) nil_chk(ordering_)) compareWithId:e withId:x] <= 0) {
      break;
    }
    (void) IOSObjectArray_Set(nil_chk(this$0_->queue_), index, e);
    index = grandParentIndex;
  }
  (void) IOSObjectArray_Set(nil_chk(this$0_->queue_), index, x);
  return index;
}

- (jint)findMinWithInt:(jint)index
               withInt:(jint)len {
  if (index >= this$0_->size_) {
    return -1;
  }
  ComGoogleCommonBasePreconditions_checkStateWithBoolean_(index > 0);
  jint limit = JavaLangMath_minWithInt_withInt_(index, this$0_->size_ - len) + len;
  jint minIndex = index;
  for (jint i = index + 1; i < limit; i++) {
    if ([self compareElementsWithInt:i withInt:minIndex] < 0) {
      minIndex = i;
    }
  }
  return minIndex;
}

- (jint)findMinChildWithInt:(jint)index {
  return [self findMinWithInt:ComGoogleCommonCollectMinMaxPriorityQueue_Heap_getLeftChildIndexWithInt_(self, index) withInt:2];
}

- (jint)findMinGrandChildWithInt:(jint)index {
  jint leftChildIndex = ComGoogleCommonCollectMinMaxPriorityQueue_Heap_getLeftChildIndexWithInt_(self, index);
  if (leftChildIndex < 0) {
    return -1;
  }
  return [self findMinWithInt:ComGoogleCommonCollectMinMaxPriorityQueue_Heap_getLeftChildIndexWithInt_(self, leftChildIndex) withInt:4];
}

- (jint)crossOverUpWithInt:(jint)index
                    withId:(id)x {
  if (index == 0) {
    (void) IOSObjectArray_Set(nil_chk(this$0_->queue_), 0, x);
    return 0;
  }
  jint parentIndex = ComGoogleCommonCollectMinMaxPriorityQueue_Heap_getParentIndexWithInt_(self, index);
  id parentElement = [this$0_ elementDataWithInt:parentIndex];
  if (parentIndex != 0) {
    jint grandparentIndex = ComGoogleCommonCollectMinMaxPriorityQueue_Heap_getParentIndexWithInt_(self, parentIndex);
    jint uncleIndex = ComGoogleCommonCollectMinMaxPriorityQueue_Heap_getRightChildIndexWithInt_(self, grandparentIndex);
    if (uncleIndex != parentIndex && ComGoogleCommonCollectMinMaxPriorityQueue_Heap_getLeftChildIndexWithInt_(self, uncleIndex) >= this$0_->size_) {
      id uncleElement = [this$0_ elementDataWithInt:uncleIndex];
      if ([((ComGoogleCommonCollectOrdering *) nil_chk(ordering_)) compareWithId:uncleElement withId:parentElement] < 0) {
        parentIndex = uncleIndex;
        parentElement = uncleElement;
      }
    }
  }
  if ([((ComGoogleCommonCollectOrdering *) nil_chk(ordering_)) compareWithId:parentElement withId:x] < 0) {
    (void) IOSObjectArray_Set(nil_chk(this$0_->queue_), index, parentElement);
    (void) IOSObjectArray_Set(this$0_->queue_, parentIndex, x);
    return parentIndex;
  }
  (void) IOSObjectArray_Set(nil_chk(this$0_->queue_), index, x);
  return index;
}

- (jint)swapWithConceptuallyLastElementWithId:(id)actualLastElement {
  jint parentIndex = ComGoogleCommonCollectMinMaxPriorityQueue_Heap_getParentIndexWithInt_(self, this$0_->size_);
  if (parentIndex != 0) {
    jint grandparentIndex = ComGoogleCommonCollectMinMaxPriorityQueue_Heap_getParentIndexWithInt_(self, parentIndex);
    jint uncleIndex = ComGoogleCommonCollectMinMaxPriorityQueue_Heap_getRightChildIndexWithInt_(self, grandparentIndex);
    if (uncleIndex != parentIndex && ComGoogleCommonCollectMinMaxPriorityQueue_Heap_getLeftChildIndexWithInt_(self, uncleIndex) >= this$0_->size_) {
      id uncleElement = [this$0_ elementDataWithInt:uncleIndex];
      if ([((ComGoogleCommonCollectOrdering *) nil_chk(ordering_)) compareWithId:uncleElement withId:actualLastElement] < 0) {
        (void) IOSObjectArray_Set(nil_chk(this$0_->queue_), uncleIndex, actualLastElement);
        (void) IOSObjectArray_Set(this$0_->queue_, this$0_->size_, uncleElement);
        return uncleIndex;
      }
    }
  }
  return this$0_->size_;
}

- (jint)crossOverWithInt:(jint)index
                  withId:(id)x {
  jint minChildIndex = [self findMinChildWithInt:index];
  if ((minChildIndex > 0) && ([((ComGoogleCommonCollectOrdering *) nil_chk(ordering_)) compareWithId:[this$0_ elementDataWithInt:minChildIndex] withId:x] < 0)) {
    (void) IOSObjectArray_Set(nil_chk(this$0_->queue_), index, [this$0_ elementDataWithInt:minChildIndex]);
    (void) IOSObjectArray_Set(nil_chk(this$0_->queue_), minChildIndex, x);
    return minChildIndex;
  }
  return [self crossOverUpWithInt:index withId:x];
}

- (jint)fillHoleAtWithInt:(jint)index {
  jint minGrandchildIndex;
  while ((minGrandchildIndex = [self findMinGrandChildWithInt:index]) > 0) {
    (void) IOSObjectArray_Set(nil_chk(this$0_->queue_), index, [this$0_ elementDataWithInt:minGrandchildIndex]);
    index = minGrandchildIndex;
  }
  return index;
}

- (jboolean)verifyIndexWithInt:(jint)i {
  return ComGoogleCommonCollectMinMaxPriorityQueue_Heap_verifyIndexWithInt_(self, i);
}

- (jint)getLeftChildIndexWithInt:(jint)i {
  return ComGoogleCommonCollectMinMaxPriorityQueue_Heap_getLeftChildIndexWithInt_(self, i);
}

- (jint)getRightChildIndexWithInt:(jint)i {
  return ComGoogleCommonCollectMinMaxPriorityQueue_Heap_getRightChildIndexWithInt_(self, i);
}

- (jint)getParentIndexWithInt:(jint)i {
  return ComGoogleCommonCollectMinMaxPriorityQueue_Heap_getParentIndexWithInt_(self, i);
}

- (jint)getGrandparentIndexWithInt:(jint)i {
  return ComGoogleCommonCollectMinMaxPriorityQueue_Heap_getGrandparentIndexWithInt_(self, i);
}

- (void)__javaClone:(ComGoogleCommonCollectMinMaxPriorityQueue_Heap *)original {
  [super __javaClone:original];
  JreRelease(this$0_);
  JreRelease(otherHeap_);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x0, -1, 0, -1, 1, -1, -1 },
    { NULL, "I", 0x0, 2, 3, -1, -1, -1, -1 },
    { NULL, "LComGoogleCommonCollectMinMaxPriorityQueue_MoveDesc;", 0x0, 4, 5, -1, 6, -1, -1 },
    { NULL, "V", 0x0, 7, 8, -1, 9, -1, -1 },
    { NULL, "I", 0x0, 10, 8, -1, 11, -1, -1 },
    { NULL, "I", 0x0, 12, 3, -1, -1, -1, -1 },
    { NULL, "I", 0x0, 13, 14, -1, -1, -1, -1 },
    { NULL, "I", 0x0, 15, 14, -1, -1, -1, -1 },
    { NULL, "I", 0x0, 16, 8, -1, 11, -1, -1 },
    { NULL, "I", 0x0, 17, 18, -1, 19, -1, -1 },
    { NULL, "I", 0x0, 20, 8, -1, 11, -1, -1 },
    { NULL, "I", 0x0, 21, 14, -1, -1, -1, -1 },
    { NULL, "Z", 0x2, 22, 14, -1, -1, -1, -1 },
    { NULL, "I", 0x2, 23, 14, -1, -1, -1, -1 },
    { NULL, "I", 0x2, 24, 14, -1, -1, -1, -1 },
    { NULL, "I", 0x2, 25, 14, -1, -1, -1, -1 },
    { NULL, "I", 0x2, 26, 14, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(initWithComGoogleCommonCollectMinMaxPriorityQueue:withComGoogleCommonCollectOrdering:);
  methods[1].selector = @selector(compareElementsWithInt:withInt:);
  methods[2].selector = @selector(tryCrossOverAndBubbleUpWithInt:withInt:withId:);
  methods[3].selector = @selector(bubbleUpWithInt:withId:);
  methods[4].selector = @selector(bubbleUpAlternatingLevelsWithInt:withId:);
  methods[5].selector = @selector(findMinWithInt:withInt:);
  methods[6].selector = @selector(findMinChildWithInt:);
  methods[7].selector = @selector(findMinGrandChildWithInt:);
  methods[8].selector = @selector(crossOverUpWithInt:withId:);
  methods[9].selector = @selector(swapWithConceptuallyLastElementWithId:);
  methods[10].selector = @selector(crossOverWithInt:withId:);
  methods[11].selector = @selector(fillHoleAtWithInt:);
  methods[12].selector = @selector(verifyIndexWithInt:);
  methods[13].selector = @selector(getLeftChildIndexWithInt:);
  methods[14].selector = @selector(getRightChildIndexWithInt:);
  methods[15].selector = @selector(getParentIndexWithInt:);
  methods[16].selector = @selector(getGrandparentIndexWithInt:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "this$0_", "LComGoogleCommonCollectMinMaxPriorityQueue;", .constantValue.asLong = 0, 0x1012, -1, -1, 27, -1 },
    { "ordering_", "LComGoogleCommonCollectOrdering;", .constantValue.asLong = 0, 0x10, -1, -1, 28, -1 },
    { "otherHeap_", "LComGoogleCommonCollectMinMaxPriorityQueue_Heap;", .constantValue.asLong = 0, 0x0, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LComGoogleCommonCollectOrdering;", "(Lcom/google/common/collect/Ordering<TE;>;)V", "compareElements", "II", "tryCrossOverAndBubbleUp", "IILNSObject;", "(IITE;)Lcom/google/common/collect/MinMaxPriorityQueue$MoveDesc<TE;>;", "bubbleUp", "ILNSObject;", "(ITE;)V", "bubbleUpAlternatingLevels", "(ITE;)I", "findMin", "findMinChild", "I", "findMinGrandChild", "crossOverUp", "swapWithConceptuallyLastElement", "LNSObject;", "(TE;)I", "crossOver", "fillHoleAt", "verifyIndex", "getLeftChildIndex", "getRightChildIndex", "getParentIndex", "getGrandparentIndex", "Lcom/google/common/collect/MinMaxPriorityQueue<TE;>;", "Lcom/google/common/collect/Ordering<TE;>;", "LComGoogleCommonCollectMinMaxPriorityQueue;" };
  static const J2ObjcClassInfo _ComGoogleCommonCollectMinMaxPriorityQueue_Heap = { "Heap", "com.google.common.collect", ptrTable, methods, fields, 7, 0x2, 17, 3, 29, -1, -1, -1, -1 };
  return &_ComGoogleCommonCollectMinMaxPriorityQueue_Heap;
}

@end

void ComGoogleCommonCollectMinMaxPriorityQueue_Heap_initWithComGoogleCommonCollectMinMaxPriorityQueue_withComGoogleCommonCollectOrdering_(ComGoogleCommonCollectMinMaxPriorityQueue_Heap *self, ComGoogleCommonCollectMinMaxPriorityQueue *outer$, ComGoogleCommonCollectOrdering *ordering) {
  self->this$0_ = outer$;
  NSObject_init(self);
  self->ordering_ = ordering;
}

ComGoogleCommonCollectMinMaxPriorityQueue_Heap *new_ComGoogleCommonCollectMinMaxPriorityQueue_Heap_initWithComGoogleCommonCollectMinMaxPriorityQueue_withComGoogleCommonCollectOrdering_(ComGoogleCommonCollectMinMaxPriorityQueue *outer$, ComGoogleCommonCollectOrdering *ordering) {
  J2OBJC_NEW_IMPL(ComGoogleCommonCollectMinMaxPriorityQueue_Heap, initWithComGoogleCommonCollectMinMaxPriorityQueue_withComGoogleCommonCollectOrdering_, outer$, ordering)
}

ComGoogleCommonCollectMinMaxPriorityQueue_Heap *create_ComGoogleCommonCollectMinMaxPriorityQueue_Heap_initWithComGoogleCommonCollectMinMaxPriorityQueue_withComGoogleCommonCollectOrdering_(ComGoogleCommonCollectMinMaxPriorityQueue *outer$, ComGoogleCommonCollectOrdering *ordering) {
  J2OBJC_CREATE_IMPL(ComGoogleCommonCollectMinMaxPriorityQueue_Heap, initWithComGoogleCommonCollectMinMaxPriorityQueue_withComGoogleCommonCollectOrdering_, outer$, ordering)
}

jboolean ComGoogleCommonCollectMinMaxPriorityQueue_Heap_verifyIndexWithInt_(ComGoogleCommonCollectMinMaxPriorityQueue_Heap *self, jint i) {
  if ((ComGoogleCommonCollectMinMaxPriorityQueue_Heap_getLeftChildIndexWithInt_(self, i) < self->this$0_->size_) && ([self compareElementsWithInt:i withInt:ComGoogleCommonCollectMinMaxPriorityQueue_Heap_getLeftChildIndexWithInt_(self, i)] > 0)) {
    return false;
  }
  if ((ComGoogleCommonCollectMinMaxPriorityQueue_Heap_getRightChildIndexWithInt_(self, i) < self->this$0_->size_) && ([self compareElementsWithInt:i withInt:ComGoogleCommonCollectMinMaxPriorityQueue_Heap_getRightChildIndexWithInt_(self, i)] > 0)) {
    return false;
  }
  if ((i > 0) && ([self compareElementsWithInt:i withInt:ComGoogleCommonCollectMinMaxPriorityQueue_Heap_getParentIndexWithInt_(self, i)] > 0)) {
    return false;
  }
  if ((i > 2) && ([self compareElementsWithInt:ComGoogleCommonCollectMinMaxPriorityQueue_Heap_getGrandparentIndexWithInt_(self, i) withInt:i] > 0)) {
    return false;
  }
  return true;
}

jint ComGoogleCommonCollectMinMaxPriorityQueue_Heap_getLeftChildIndexWithInt_(ComGoogleCommonCollectMinMaxPriorityQueue_Heap *self, jint i) {
  return i * 2 + 1;
}

jint ComGoogleCommonCollectMinMaxPriorityQueue_Heap_getRightChildIndexWithInt_(ComGoogleCommonCollectMinMaxPriorityQueue_Heap *self, jint i) {
  return i * 2 + 2;
}

jint ComGoogleCommonCollectMinMaxPriorityQueue_Heap_getParentIndexWithInt_(ComGoogleCommonCollectMinMaxPriorityQueue_Heap *self, jint i) {
  return (i - 1) / 2;
}

jint ComGoogleCommonCollectMinMaxPriorityQueue_Heap_getGrandparentIndexWithInt_(ComGoogleCommonCollectMinMaxPriorityQueue_Heap *self, jint i) {
  return ComGoogleCommonCollectMinMaxPriorityQueue_Heap_getParentIndexWithInt_(self, ComGoogleCommonCollectMinMaxPriorityQueue_Heap_getParentIndexWithInt_(self, i));
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComGoogleCommonCollectMinMaxPriorityQueue_Heap)

@implementation ComGoogleCommonCollectMinMaxPriorityQueue_QueueIterator

- (instancetype)initWithComGoogleCommonCollectMinMaxPriorityQueue:(ComGoogleCommonCollectMinMaxPriorityQueue *)outer$ {
  ComGoogleCommonCollectMinMaxPriorityQueue_QueueIterator_initWithComGoogleCommonCollectMinMaxPriorityQueue_(self, outer$);
  return self;
}

- (jboolean)hasNext {
  ComGoogleCommonCollectMinMaxPriorityQueue_QueueIterator_checkModCount(self);
  ComGoogleCommonCollectMinMaxPriorityQueue_QueueIterator_nextNotInSkipMeWithInt_(self, cursor_ + 1);
  return (nextCursor_ < [this$0_ size]) || ((forgetMeNot_ != nil) && ![((id<JavaUtilQueue>) nil_chk(forgetMeNot_)) isEmpty]);
}

- (id)next {
  ComGoogleCommonCollectMinMaxPriorityQueue_QueueIterator_checkModCount(self);
  ComGoogleCommonCollectMinMaxPriorityQueue_QueueIterator_nextNotInSkipMeWithInt_(self, cursor_ + 1);
  if (nextCursor_ < [this$0_ size]) {
    cursor_ = nextCursor_;
    canRemove_ = true;
    return [this$0_ elementDataWithInt:cursor_];
  }
  else if (forgetMeNot_ != nil) {
    cursor_ = [this$0_ size];
    lastFromForgetMeNot_ = [((id<JavaUtilQueue>) nil_chk(forgetMeNot_)) poll];
    if (lastFromForgetMeNot_ != nil) {
      canRemove_ = true;
      return lastFromForgetMeNot_;
    }
  }
  @throw new_JavaUtilNoSuchElementException_initWithNSString_(@"iterator moved past last element in queue.");
}

- (void)remove {
  ComGoogleCommonCollectCollectPreconditions_checkRemoveWithBoolean_(canRemove_);
  ComGoogleCommonCollectMinMaxPriorityQueue_QueueIterator_checkModCount(self);
  canRemove_ = false;
  expectedModCount_++;
  if (cursor_ < [this$0_ size]) {
    ComGoogleCommonCollectMinMaxPriorityQueue_MoveDesc *moved = [this$0_ removeAtWithInt:cursor_];
    if (moved != nil) {
      if (forgetMeNot_ == nil) {
        forgetMeNot_ = new_JavaUtilArrayDeque_init();
        skipMe_ = new_JavaUtilArrayList_initWithInt_(3);
      }
      if (!ComGoogleCommonCollectMinMaxPriorityQueue_QueueIterator_foundAndRemovedExactReferenceWithJavaLangIterable_withId_(self, skipMe_, moved->toTrickle_)) {
        [((id<JavaUtilQueue>) nil_chk(forgetMeNot_)) addWithId:moved->toTrickle_];
      }
      if (!ComGoogleCommonCollectMinMaxPriorityQueue_QueueIterator_foundAndRemovedExactReferenceWithJavaLangIterable_withId_(self, forgetMeNot_, moved->replaced_)) {
        [((id<JavaUtilList>) nil_chk(skipMe_)) addWithId:moved->replaced_];
      }
    }
    cursor_--;
    nextCursor_--;
  }
  else {
    ComGoogleCommonBasePreconditions_checkStateWithBoolean_(ComGoogleCommonCollectMinMaxPriorityQueue_QueueIterator_removeExactWithId_(self, lastFromForgetMeNot_));
    lastFromForgetMeNot_ = nil;
  }
}

- (jboolean)foundAndRemovedExactReferenceWithJavaLangIterable:(id<JavaLangIterable>)elements
                                                       withId:(id)target {
  return ComGoogleCommonCollectMinMaxPriorityQueue_QueueIterator_foundAndRemovedExactReferenceWithJavaLangIterable_withId_(self, elements, target);
}

- (jboolean)removeExactWithId:(id)target {
  return ComGoogleCommonCollectMinMaxPriorityQueue_QueueIterator_removeExactWithId_(self, target);
}

- (void)checkModCount {
  ComGoogleCommonCollectMinMaxPriorityQueue_QueueIterator_checkModCount(self);
}

- (void)nextNotInSkipMeWithInt:(jint)c {
  ComGoogleCommonCollectMinMaxPriorityQueue_QueueIterator_nextNotInSkipMeWithInt_(self, c);
}

- (void)forEachRemainingWithJavaUtilFunctionConsumer:(id<JavaUtilFunctionConsumer>)arg0 {
  JavaUtilIterator_forEachRemainingWithJavaUtilFunctionConsumer_(self, arg0);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x2, -1, -1, -1, -1, -1, -1 },
    { NULL, "Z", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, -1, -1, -1, 0, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "Z", 0x2, 1, 2, -1, 3, -1, -1 },
    { NULL, "Z", 0x2, 4, 5, -1, -1, -1, -1 },
    { NULL, "V", 0x2, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 6, 7, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(initWithComGoogleCommonCollectMinMaxPriorityQueue:);
  methods[1].selector = @selector(hasNext);
  methods[2].selector = @selector(next);
  methods[3].selector = @selector(remove);
  methods[4].selector = @selector(foundAndRemovedExactReferenceWithJavaLangIterable:withId:);
  methods[5].selector = @selector(removeExactWithId:);
  methods[6].selector = @selector(checkModCount);
  methods[7].selector = @selector(nextNotInSkipMeWithInt:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "this$0_", "LComGoogleCommonCollectMinMaxPriorityQueue;", .constantValue.asLong = 0, 0x1012, -1, -1, 8, -1 },
    { "cursor_", "I", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "nextCursor_", "I", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "expectedModCount_", "I", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "forgetMeNot_", "LJavaUtilQueue;", .constantValue.asLong = 0, 0x2, -1, -1, 9, -1 },
    { "skipMe_", "LJavaUtilList;", .constantValue.asLong = 0, 0x2, -1, -1, 10, -1 },
    { "lastFromForgetMeNot_", "LNSObject;", .constantValue.asLong = 0, 0x2, -1, -1, 11, -1 },
    { "canRemove_", "Z", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "()TE;", "foundAndRemovedExactReference", "LJavaLangIterable;LNSObject;", "(Ljava/lang/Iterable<TE;>;TE;)Z", "removeExact", "LNSObject;", "nextNotInSkipMe", "I", "Lcom/google/common/collect/MinMaxPriorityQueue<TE;>;", "Ljava/util/Queue<TE;>;", "Ljava/util/List<TE;>;", "TE;", "LComGoogleCommonCollectMinMaxPriorityQueue;", "Ljava/lang/Object;Ljava/util/Iterator<TE;>;" };
  static const J2ObjcClassInfo _ComGoogleCommonCollectMinMaxPriorityQueue_QueueIterator = { "QueueIterator", "com.google.common.collect", ptrTable, methods, fields, 7, 0x2, 8, 8, 12, -1, -1, 13, -1 };
  return &_ComGoogleCommonCollectMinMaxPriorityQueue_QueueIterator;
}

@end

void ComGoogleCommonCollectMinMaxPriorityQueue_QueueIterator_initWithComGoogleCommonCollectMinMaxPriorityQueue_(ComGoogleCommonCollectMinMaxPriorityQueue_QueueIterator *self, ComGoogleCommonCollectMinMaxPriorityQueue *outer$) {
  self->this$0_ = outer$;
  NSObject_init(self);
  self->cursor_ = -1;
  self->nextCursor_ = -1;
  self->expectedModCount_ = outer$->modCount_;
}

ComGoogleCommonCollectMinMaxPriorityQueue_QueueIterator *new_ComGoogleCommonCollectMinMaxPriorityQueue_QueueIterator_initWithComGoogleCommonCollectMinMaxPriorityQueue_(ComGoogleCommonCollectMinMaxPriorityQueue *outer$) {
  J2OBJC_NEW_IMPL(ComGoogleCommonCollectMinMaxPriorityQueue_QueueIterator, initWithComGoogleCommonCollectMinMaxPriorityQueue_, outer$)
}

ComGoogleCommonCollectMinMaxPriorityQueue_QueueIterator *create_ComGoogleCommonCollectMinMaxPriorityQueue_QueueIterator_initWithComGoogleCommonCollectMinMaxPriorityQueue_(ComGoogleCommonCollectMinMaxPriorityQueue *outer$) {
  J2OBJC_CREATE_IMPL(ComGoogleCommonCollectMinMaxPriorityQueue_QueueIterator, initWithComGoogleCommonCollectMinMaxPriorityQueue_, outer$)
}

jboolean ComGoogleCommonCollectMinMaxPriorityQueue_QueueIterator_foundAndRemovedExactReferenceWithJavaLangIterable_withId_(ComGoogleCommonCollectMinMaxPriorityQueue_QueueIterator *self, id<JavaLangIterable> elements, id target) {
  for (id<JavaUtilIterator> it = [((id<JavaLangIterable>) nil_chk(elements)) iterator]; [((id<JavaUtilIterator>) nil_chk(it)) hasNext]; ) {
    id element = [it next];
    if (element == target) {
      [it remove];
      return true;
    }
  }
  return false;
}

jboolean ComGoogleCommonCollectMinMaxPriorityQueue_QueueIterator_removeExactWithId_(ComGoogleCommonCollectMinMaxPriorityQueue_QueueIterator *self, id target) {
  for (jint i = 0; i < self->this$0_->size_; i++) {
    if (IOSObjectArray_Get(nil_chk(self->this$0_->queue_), i) == target) {
      (void) [self->this$0_ removeAtWithInt:i];
      return true;
    }
  }
  return false;
}

void ComGoogleCommonCollectMinMaxPriorityQueue_QueueIterator_checkModCount(ComGoogleCommonCollectMinMaxPriorityQueue_QueueIterator *self) {
  if (self->this$0_->modCount_ != self->expectedModCount_) {
    @throw new_JavaUtilConcurrentModificationException_init();
  }
}

void ComGoogleCommonCollectMinMaxPriorityQueue_QueueIterator_nextNotInSkipMeWithInt_(ComGoogleCommonCollectMinMaxPriorityQueue_QueueIterator *self, jint c) {
  if (self->nextCursor_ < c) {
    if (self->skipMe_ != nil) {
      while (c < [self->this$0_ size] && ComGoogleCommonCollectMinMaxPriorityQueue_QueueIterator_foundAndRemovedExactReferenceWithJavaLangIterable_withId_(self, self->skipMe_, [self->this$0_ elementDataWithInt:c])) {
        c++;
      }
    }
    self->nextCursor_ = c;
  }
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComGoogleCommonCollectMinMaxPriorityQueue_QueueIterator)
