//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/Personal/Documents/raspi-config/client-framework/build/j2oSources/com/google/common/collect/RegularImmutableAsList.java
//

#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "com/google/common/collect/ImmutableAsList.h"
#include "com/google/common/collect/ImmutableCollection.h"
#include "com/google/common/collect/ImmutableList.h"
#include "com/google/common/collect/RegularImmutableAsList.h"
#include "com/google/common/collect/UnmodifiableListIterator.h"
#include "java/util/function/Consumer.h"

@interface ComGoogleCommonCollectRegularImmutableAsList () {
 @public
  ComGoogleCommonCollectImmutableCollection *delegate_;
  ComGoogleCommonCollectImmutableList *delegateList_;
}

@end

J2OBJC_FIELD_SETTER(ComGoogleCommonCollectRegularImmutableAsList, delegate_, ComGoogleCommonCollectImmutableCollection *)
J2OBJC_FIELD_SETTER(ComGoogleCommonCollectRegularImmutableAsList, delegateList_, ComGoogleCommonCollectImmutableList *)

@implementation ComGoogleCommonCollectRegularImmutableAsList

- (instancetype)initWithComGoogleCommonCollectImmutableCollection:(ComGoogleCommonCollectImmutableCollection *)delegate
                          withComGoogleCommonCollectImmutableList:(ComGoogleCommonCollectImmutableList *)delegateList {
  ComGoogleCommonCollectRegularImmutableAsList_initWithComGoogleCommonCollectImmutableCollection_withComGoogleCommonCollectImmutableList_(self, delegate, delegateList);
  return self;
}

- (instancetype)initWithComGoogleCommonCollectImmutableCollection:(ComGoogleCommonCollectImmutableCollection *)delegate
                                                withNSObjectArray:(IOSObjectArray *)array {
  ComGoogleCommonCollectRegularImmutableAsList_initWithComGoogleCommonCollectImmutableCollection_withNSObjectArray_(self, delegate, array);
  return self;
}

- (ComGoogleCommonCollectImmutableCollection *)delegateCollection {
  return delegate_;
}

- (ComGoogleCommonCollectImmutableList *)delegateList {
  return delegateList_;
}

- (ComGoogleCommonCollectUnmodifiableListIterator *)listIteratorWithInt:(jint)index {
  return [((ComGoogleCommonCollectImmutableList *) nil_chk(delegateList_)) listIteratorWithInt:index];
}

- (void)forEachWithJavaUtilFunctionConsumer:(id<JavaUtilFunctionConsumer>)action {
  [((ComGoogleCommonCollectImmutableList *) nil_chk(delegateList_)) forEachWithJavaUtilFunctionConsumer:action];
}

- (jint)copyIntoArrayWithNSObjectArray:(IOSObjectArray *)dst
                               withInt:(jint)offset {
  return [((ComGoogleCommonCollectImmutableList *) nil_chk(delegateList_)) copyIntoArrayWithNSObjectArray:dst withInt:offset];
}

- (id)getWithInt:(jint)index {
  return [((ComGoogleCommonCollectImmutableList *) nil_chk(delegateList_)) getWithInt:index];
}

- (NSUInteger)countByEnumeratingWithState:(NSFastEnumerationState *)state objects:(__unsafe_unretained id *)stackbuf count:(NSUInteger)len {
  return JreDefaultFastEnumeration(self, state, stackbuf, len);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x0, -1, 0, -1, 1, -1, -1 },
    { NULL, NULL, 0x0, -1, 2, -1, 3, -1, -1 },
    { NULL, "LComGoogleCommonCollectImmutableCollection;", 0x0, -1, -1, -1, 4, -1, -1 },
    { NULL, "LComGoogleCommonCollectImmutableList;", 0x0, -1, -1, -1, 5, -1, -1 },
    { NULL, "LComGoogleCommonCollectUnmodifiableListIterator;", 0x1, 6, 7, -1, 8, -1, -1 },
    { NULL, "V", 0x1, 9, 10, -1, 11, -1, -1 },
    { NULL, "I", 0x0, 12, 13, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, 14, 7, -1, 15, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(initWithComGoogleCommonCollectImmutableCollection:withComGoogleCommonCollectImmutableList:);
  methods[1].selector = @selector(initWithComGoogleCommonCollectImmutableCollection:withNSObjectArray:);
  methods[2].selector = @selector(delegateCollection);
  methods[3].selector = @selector(delegateList);
  methods[4].selector = @selector(listIteratorWithInt:);
  methods[5].selector = @selector(forEachWithJavaUtilFunctionConsumer:);
  methods[6].selector = @selector(copyIntoArrayWithNSObjectArray:withInt:);
  methods[7].selector = @selector(getWithInt:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "delegate_", "LComGoogleCommonCollectImmutableCollection;", .constantValue.asLong = 0, 0x12, -1, -1, 16, -1 },
    { "delegateList_", "LComGoogleCommonCollectImmutableList;", .constantValue.asLong = 0, 0x12, -1, -1, 17, -1 },
  };
  static const void *ptrTable[] = { "LComGoogleCommonCollectImmutableCollection;LComGoogleCommonCollectImmutableList;", "(Lcom/google/common/collect/ImmutableCollection<TE;>;Lcom/google/common/collect/ImmutableList<+TE;>;)V", "LComGoogleCommonCollectImmutableCollection;[LNSObject;", "(Lcom/google/common/collect/ImmutableCollection<TE;>;[Ljava/lang/Object;)V", "()Lcom/google/common/collect/ImmutableCollection<TE;>;", "()Lcom/google/common/collect/ImmutableList<+TE;>;", "listIterator", "I", "(I)Lcom/google/common/collect/UnmodifiableListIterator<TE;>;", "forEach", "LJavaUtilFunctionConsumer;", "(Ljava/util/function/Consumer<-TE;>;)V", "copyIntoArray", "[LNSObject;I", "get", "(I)TE;", "Lcom/google/common/collect/ImmutableCollection<TE;>;", "Lcom/google/common/collect/ImmutableList<+TE;>;", "<E:Ljava/lang/Object;>Lcom/google/common/collect/ImmutableAsList<TE;>;" };
  static const J2ObjcClassInfo _ComGoogleCommonCollectRegularImmutableAsList = { "RegularImmutableAsList", "com.google.common.collect", ptrTable, methods, fields, 7, 0x0, 8, 2, -1, -1, -1, 18, -1 };
  return &_ComGoogleCommonCollectRegularImmutableAsList;
}

@end

void ComGoogleCommonCollectRegularImmutableAsList_initWithComGoogleCommonCollectImmutableCollection_withComGoogleCommonCollectImmutableList_(ComGoogleCommonCollectRegularImmutableAsList *self, ComGoogleCommonCollectImmutableCollection *delegate, ComGoogleCommonCollectImmutableList *delegateList) {
  ComGoogleCommonCollectImmutableAsList_init(self);
  self->delegate_ = delegate;
  self->delegateList_ = delegateList;
}

ComGoogleCommonCollectRegularImmutableAsList *new_ComGoogleCommonCollectRegularImmutableAsList_initWithComGoogleCommonCollectImmutableCollection_withComGoogleCommonCollectImmutableList_(ComGoogleCommonCollectImmutableCollection *delegate, ComGoogleCommonCollectImmutableList *delegateList) {
  J2OBJC_NEW_IMPL(ComGoogleCommonCollectRegularImmutableAsList, initWithComGoogleCommonCollectImmutableCollection_withComGoogleCommonCollectImmutableList_, delegate, delegateList)
}

ComGoogleCommonCollectRegularImmutableAsList *create_ComGoogleCommonCollectRegularImmutableAsList_initWithComGoogleCommonCollectImmutableCollection_withComGoogleCommonCollectImmutableList_(ComGoogleCommonCollectImmutableCollection *delegate, ComGoogleCommonCollectImmutableList *delegateList) {
  J2OBJC_CREATE_IMPL(ComGoogleCommonCollectRegularImmutableAsList, initWithComGoogleCommonCollectImmutableCollection_withComGoogleCommonCollectImmutableList_, delegate, delegateList)
}

void ComGoogleCommonCollectRegularImmutableAsList_initWithComGoogleCommonCollectImmutableCollection_withNSObjectArray_(ComGoogleCommonCollectRegularImmutableAsList *self, ComGoogleCommonCollectImmutableCollection *delegate, IOSObjectArray *array) {
  ComGoogleCommonCollectRegularImmutableAsList_initWithComGoogleCommonCollectImmutableCollection_withComGoogleCommonCollectImmutableList_(self, delegate, ComGoogleCommonCollectImmutableList_asImmutableListWithNSObjectArray_(array));
}

ComGoogleCommonCollectRegularImmutableAsList *new_ComGoogleCommonCollectRegularImmutableAsList_initWithComGoogleCommonCollectImmutableCollection_withNSObjectArray_(ComGoogleCommonCollectImmutableCollection *delegate, IOSObjectArray *array) {
  J2OBJC_NEW_IMPL(ComGoogleCommonCollectRegularImmutableAsList, initWithComGoogleCommonCollectImmutableCollection_withNSObjectArray_, delegate, array)
}

ComGoogleCommonCollectRegularImmutableAsList *create_ComGoogleCommonCollectRegularImmutableAsList_initWithComGoogleCommonCollectImmutableCollection_withNSObjectArray_(ComGoogleCommonCollectImmutableCollection *delegate, IOSObjectArray *array) {
  J2OBJC_CREATE_IMPL(ComGoogleCommonCollectRegularImmutableAsList, initWithComGoogleCommonCollectImmutableCollection_withNSObjectArray_, delegate, array)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComGoogleCommonCollectRegularImmutableAsList)
